-- ⚠️ HISTORICAL — SUPERSEDED. DO NOT RUN ON A LIVE DATABASE.
--
-- This put validation_secret directly on `venues`, which has a public
-- `using (true)` SELECT policy (schema.sql) — RLS is row-level, not
-- column-level, so this let anyone with the shipped anon key read every
-- venue's door-staff secret via `select validation_secret from venues`,
-- defeating /api/passes/redeem and /api/venue/stats' entire auth model.
--
-- Superseded by venue_secrets_lockdown.sql (moves the secret to its own
-- zero-policy `venue_secrets` table and drops this column from venues).
-- Run that file instead. Kept here only as a historical record of what the
-- original per-venue-secret migration looked like.
