import type { Venue } from "@/types";

/**
 * AUTO-GENERATED by scripts/enrich-venues.ts — do not edit the live fields
 * by hand. Curated insider fields are preserved across runs; run `npm run
 * enrich` to refresh Google-sourced data. Last run: 2026-07-06T20:07:03.704Z
 */
export const VENUES: Venue[] = [
  {
    "id": "liv-miami",
    "slug": "liv-miami",
    "name": "LIV Miami",
    "type": "club",
    "neighborhood": "South Beach",
    "address": "4441 Collins Ave, Miami Beach, FL 33140, USA",
    "lat": 25.8180403,
    "lng": -80.1223972,
    "hook": "The superclub. World-class DJs, celebrity sightings, zero chill.",
    "description": "Inside the Fontainebleau, LIV is Miami's most famous nightclub — a cathedral of sound where the world's top DJs headline and the energy peaks after 1 AM. Dress sharp, arrive with a plan, and expect a night you'll talk about for years.",
    "rating": 3.3,
    "reviewCount": 2052,
    "coverMen": 60,
    "coverWomen": 40,
    "priceTier": 4,
    "avgSpend": 150,
    "openTime": "23:00",
    "closeTime": "05:00",
    "happyHourUntil": null,
    "musicGenres": [
      "edm",
      "house",
      "hip_hop"
    ],
    "vibes": [
      "High energy",
      "Celebrity",
      "Bottle service",
      "Dress to impress"
    ],
    "dressCode": "Upscale — no shorts, no sneakers",
    "parking": "Valet at Fontainebleau ($30)",
    "crowdLevel": "packed",
    "bestArrivalTime": "11:30 PM",
    "peakHours": "1 AM – 3 AM",
    "popularDrinks": [
      {
        "name": "Grey Goose bottle",
        "price": 650,
        "emoji": "🍾"
      },
      {
        "name": "Espresso Martini",
        "price": 24,
        "emoji": "🍸"
      }
    ],
    "upcomingEvents": [],
    "emoji": "🔥",
    "imageUrl": null,
    "instagramHandle": "livmiami",
    "isTrending": true,
    "isOpenNow": false,
    "live": {
      "placeId": "ChIJoWHkOGqz2YgRFI7KBOyVT80",
      "businessStatus": "OPERATIONAL",
      "googleMapsUri": "https://maps.google.com/?cid=14794208141860572692&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
      "weekdayText": [
        "Monday: Closed",
        "Tuesday: Closed",
        "Wednesday: Closed",
        "Thursday: 11:00 PM – 5:00 AM",
        "Friday: 11:00 PM – 5:00 AM",
        "Saturday: 11:00 PM – 5:00 AM",
        "Sunday: 11:00 PM – 5:00 AM"
      ],
      "photoRefs": [
        "places/ChIJoWHkOGqz2YgRFI7KBOyVT80/photos/AaVGc3nl_IqjreaanPkJQ601jsdiZSwfRhakn4pVg-W-TfdCu7_cvnTUifHnEx_FocZVCntpQ4iwZy5KDQvQQBz5R97WRlQK27QG7tGOoDGV97WTuPY1vo_tDLgyP0eE13jW3Zf956pSKaVTtX-YaubFg26fNLfKdZWie2p7w3pcEzjQcGjDrpQMRoFu_TifnrfCkjuT2CoB8SivDGSJqFOLmBr6RjNBeoEQKLRkbzpJBHepO2zK7u_3v6nkWwKZ-vzKV1U7rPWZ3HvGqpYt2YUuHeXDHEN9r5VKFE_g951YADrrXWHpO9lwFOzoBvQUGR4NCQfCzgsqY4BHS-mzzeydlAKUPOuuasPalSG-cog_RBRUrvMGJrRfV4uN_H5DQ8anqN0Ywns_AyUsMyvnysr4pNE6So8DKMMuVREMucJaKNCZ0g",
        "places/ChIJoWHkOGqz2YgRFI7KBOyVT80/photos/AaVGc3n3A9PWPXSeEg0RLki5NEHGwQ6oB8BoqUjzUg1m1wqQWS0OIdzAOe6ALq2xxScnn_sKK6x9KqohCx0WVQKqaMgHa7_nbTNL9Txd1vxj6FBKGFqgJb27P5jckOFcWGwcLWGr3NE-svxQZnCd62EspI-caor27r2Hy-rGjv2W8dDUjTIXT20UqBH39w84ofVBN8Nm1qHpaws7qTBLKpECHkMHK0vFhWqozPYe0JfuQf4YkfgaNXnm1z5y24PTNzZcuLRzIwBAqxevQNtCNfDComscPKpCylbXwsqfZO0nNU1MwR5w8l83NKFX1lAZjFQUJ1L7zEqbLTRKQJLSIBFBwPKrL1IeyFyJ-wSuWJyXEcnSimO72iGpNU0l7NE7VhVvYZS2wt8Bll8pwJ0UtN6tbIXqSnc19Z9e5F61sDwoTxTIW4s",
        "places/ChIJoWHkOGqz2YgRFI7KBOyVT80/photos/AaVGc3kXKVfAyIkl7uvDUgqujTkjVurqg2Zob3yW8rEJ9XmnbCTH95NumK6de22LIbV8dwlv8aDDl0f2OGKpjBMRzv4-QoQw89cZzukzsi5-wn7C-ol8jYx3RfXsGseF9VmrL06RiFCMnoAgk8CH88DKXwub1MCrhsM_YdwbEpUhb1pjxcrTEAYWClJ_1ZYHRnJagqZuX-0aqFaSE5WwxnFkp13Jc5VIkrTEjg_6A2T0jNOZO2hDmg84rwYIF8bqjqafbL31XYbrrC3bvMLkW5wrIDP9A_t2iUc8_wXCpPxC2UsaH1M4v-SW1oV35FowbEP3RZD8Nno-J9IQRMvjWM01xONU6FO5bKybkGhNn_-yPGcT6iJXYpsWLfx1XgNru0OiO9xuA8k1_YSHKwi5LpDjIwWIdkAMMvbi5TEeBFqm-XQ6nfhZbRIj0O2601u3Ix1g",
        "places/ChIJoWHkOGqz2YgRFI7KBOyVT80/photos/AaVGc3k73G9qSvYs3AhcDTY4i53GA-4mA8fRQrGvF2s3EmQlZItDW4gQjtDz0ovLvBdUjBkCdv1KSKVNhWU46IFaWdI9uIYYjcyaeQUJai9muL0wzK3KU25mp6EuMG4Mmy0ergxqNKeHvWtklFQv2gRWijC0dTMUs33Xr7pIwme5gQP240Dj24IA1x4il5jDtGQ-VZzT5vekcg33K8ctjZYC-x2uoZz5EEcUnqjOdWWh2HuSFLtSBVFTRft9S8deeuj1uEEpX8Ns3Bl3BmvjCVPJSCesmm7bKT_Svd2n-5Vdc6FfLj5b8gkErHB-Ah_yUJHaV_uJ2PojyvPvinEIM788p2PPC_uSG1ZZbfq6xKsR0xRbtX2r9d9Cd8r8O0wFw1JNd3QrARbcIVLr8cHh4fOVaFL-6aldq-n0Ok9LuQTbkocbrcekxX0tA-zOT-rB_A",
        "places/ChIJoWHkOGqz2YgRFI7KBOyVT80/photos/AaVGc3k8h2ijcxhrQ29ZM4P1eBU8Cxozpbnvxsm0FLxkHGdi2KV2jH_7Nc82FwQ5CGvUd_e2KxaMN1x6PRGPz5-vWbJS-8nn307shc8h8eSYRQCJGhEzCdusoPbtKsMlYgZ2_94wvqFmYWuHOVhjXcntejN99IFD6xc2RXtWgrNWNRBHVLxYZuMLRaoMPScVznMScRGB1ZsMnYsxvIy5mJM2KTXoPNyvgBFYim8a7JCHOaWE6hhYqz2tlUx9Y_skWuReMhp0tvPMm7dFn3Q3wzJLnlWdCUIneji1iASBVTVskGQEquH2g5wqSaU3oR4QqrLwqNFoinOmM775EjJKDdUZdnYfFSS189uBpO7WPfNOXMNchD5y8V24ifJ-BljBNgiX2Ty-1-TtLZRlvcIP1R8aqNyyrcAkBclPX0f4IHwZDmsisMUB",
        "places/ChIJoWHkOGqz2YgRFI7KBOyVT80/photos/AaVGc3lvb8kqjGUUSJKlIQ761Q4p93CfdJ7TWZtUMVsTZWEYP5VtGn5bSdD2dxiPR_RnAESO1rPblv7KX0Ztd0TqD-OFbgLwxe9p4bLt7BmpSJcgNYr4kMOAw-s65sUqxpPizrWRXa_TRKKnTxjtHVVHT1pwcFB0Rf8HmnAI3iuR1XEU6zKQndGeZD1RAeaoIW8_1r5Ar-OKq9FMYVRrQfzdJoHtruV5T1K78sMcHwggW1aPt6pr7902qqh6ewAvE576XgnQ_oDg1tOkRXh-rar7LJ0beQ8HqUsrZM7Q6aKEBSfyEw1282LtevkIl1fwTlhQre9I0EhLZFiOo3FAbej51YUgKy4G1BXbdDC-C643wn_rg1q_Wj9aynvcwVS8zcasaaMdqt0VbNTVwiw5Dwmv-AigNhErFGHGp8T7J1W68hM4v6ZBjmZ9WSAQzgHt1NVx",
        "places/ChIJoWHkOGqz2YgRFI7KBOyVT80/photos/AaVGc3nOSUTrMDkF2XunqnsgHEkowi31da7rQOV6vIvdy1wObLUED9ORMfUpmYZ2LB4OsV_4vxHmZGi5zqvJmb449yJK_tijsR08ClLRrQociNZz2lgmuimHVvzUSqz0AhBvRMK5AQhSzLT8forZVfYUDjSLMQWSBSX_km3X3V4DzIGyzT3fcavA39c-7GCpZHrP5gvsQDEnQgxQfoAz73Se8ivKDapFXA9VtfeBxUq_W8SkDUtf76QVfSHeSH0BEXNfFcN7NU59imEUad7hAllYzW0LchVJT4n-Z-1xgwKw8LlnxFpE_lvpg_RljCz3Cu7O8nvSyMI5Uu-YkYIQZfL_zGpB9jqzWkUCWW5OlrhzQVQTmaPk663wLC4o7Ua-VChOSvhssI8sUBlU8fF-I1Cor7nWy0KcDruu2EP9G1DqyRP8Vw",
        "places/ChIJoWHkOGqz2YgRFI7KBOyVT80/photos/AaVGc3kvAVQN_pXMLagqs8cQBFEtc4vRjaMjxdAY0c6bHRZYOpUqceKxLdgCt50etbT7ES5xPH7fLag9t6LOHRYQ9A6-b1oMnFL_9k4eeY2275RYvzRcwYdi6eR0d4AxJZRPtX5ocE6gCSSKa8i_yhUseozcuDMijuzT-LPZ7yknNlNHo_6PjbqqH6hd7b24YGuRpVETwshv83Sr9UF7rDlkAOtrQ287uEXU5mY8te5Y5mn2meAv9OUPFcxeap2ZH-1wS3cSjSF2f9d78xq780icAHc-Ng_aZgA3bXU8bfWzQFaewMqXl2d7bY_hvASV_TpOEtmzyMMTMYIq0kKf0h8_VCgtKM9E_kvR3Ur_9jgTM7q93fiNwfUlWYqzHQGkiothiKTRMX_E_mSNGY4Rbmj8ysx7e5fKDJGBI8lodUV_z18uPP7oQnH9mc_Kcd6O2Gw2",
        "places/ChIJoWHkOGqz2YgRFI7KBOyVT80/photos/AaVGc3nWbRwgBjCXxdXmKlYGDl14u5HJjtxHrtltVCgnuue-DZAqD_X4mVJQuZI16SBpsByVKdDU0U5Y2z3gtSExpRVYnoin_Kbe1oP6-kie3eSlixJTi3JOPbqozNaDDuUx3etTEV9eoJiK7CR1ocVzqEMXKw9fELdOKhcXhhOWEFkkgNlGHQUVi9FfmbxC4EvQufnE_JlG32PxdaaC3Ct5KpHwo8cdSKj1-94dDqFMqCenl1IN7zMEjUlT9sOUSnaJyvb_r61ncRNlUm7LmVLToXS6bNw02IHoKZ6D9bie27vELRckGwBaZL3rS0_78ko9kLg-VGqguVmW7jEivNPal3ZepWOLpQYuqLPuLyM9EZ8CvBP2Gf7S3rkwaoMzvEStto07u97F5QXq8WuZd8ZiYuliSf80gfJL5MbakhISXIXRBJA5",
        "places/ChIJoWHkOGqz2YgRFI7KBOyVT80/photos/AaVGc3kUkjLbrU6PFC6K_tkEcOgzncGYZmMYlV1qiodnOzi5wpLIS21h2uvR6jXxqlOM8pJxj-XCENOxJYQqZIXAeRdj5VWXp2t95PNVKSdyaJH7L0xgeS3Bjde3pyLX14aAiVWzfkch-r_wnnz80-JH-3ZXlInY_nbrimHaJTAicPpfG2TT_C_mVB_G7UVFPnj-mthbJYAsLYtU42pFi9MnppqBex0R_feVJGOeAUv6L4mvg-OQdSzW23LQJLUC0LeDxklk0MQr-p7HWhk0hyX1tD66Ys4uFlW7Ph4BEXX2bAcWgbRnpgV3ZpqpYVW9_qcSJieYRBlTqsXXuuieNbrWZfSBQYNbTjzez_5QXT768kI468kceQenVgR77U5fpBWy9JfKhLUwN4s0aOtysqMdsVUIndhoWErXl2UrcqczamY"
      ],
      "lastVerified": "2026-07-06T20:07:01.087Z",
      "editorialSummary": "Trendy, opulent Fontainebleau Hotel club where DJs spin at parties that attract celebs & VIPs.",
      "primaryType": "Night Club",
      "priceLevel": "PRICE_LEVEL_VERY_EXPENSIVE",
      "phone": "(305) 674-4680",
      "website": "https://www.livnightclub.com/miami/",
      "amenities": {
        "reservable": true,
        "outdoorSeating": false,
        "liveMusic": true,
        "goodForGroups": true,
        "servesCocktails": true,
        "servesBeer": true,
        "servesWine": true,
        "restroom": true,
        "wheelchairAccessible": true
      },
      "reviews": [
        {
          "author": "J Oviedo",
          "authorPhoto": "https://lh3.googleusercontent.com/a/ACg8ocK0nssJAZylWS9I-IUeGC39DxeKafNql26X-qWNyD3NJsGpdNI=s128-c0x00000000-cc-rp-mo",
          "rating": 1,
          "text": "I went to LIV Miami for Pedro Sampaio's concert, and honestly, the experience was extremely disappointing. It was surprising to see an artist like Pedro Sampaio, who is known for supporting the LGBTQ+ community, performing at a venue that felt anything but welcoming.\n\nA friend of mine and his group had VIP tickets and access to a table area, but they were denied entry because the group consisted entirely of men. Staff told them they would only be allowed in if they committed to spending at least $2,000 on table service, which felt completely unreasonable and excessive. When they declined, they were simply not allowed to enter.\n\nInside the venue, the security staff made the experience even worse. They constantly pushed and monitored people whenever someone was entering or leaving an area, often speaking in a rude and aggressive manner and telling guests to move out of the way as if they were an inconvenience. There was very little professionalism or respect shown toward attendees.\n\nWhat made the situation even more frustrating was that security seemed to ignore other guests who were openly smoking marijuana and blowing smoke into the crowd, creating discomfort for those around them.\n\nOverall, this was one of the least welcoming venues I have ever visited. The atmosphere felt hostile, especially toward groups of men, and it certainly did not feel inclusive. I would never return, even for a regular party. If an artist I like performs at LIV again, I would seriously consider skipping the event rather than risk another experience like this.",
          "relativeTime": "a month ago"
        },
        {
          "author": "Wade Z",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjVQRUr0j4ThaBUhJY0AF1EIxdBaIeQhadO4qTBiKWAX2P8lFPZysA=s128-c0x00000000-cc-rp-mo-ba6",
          "rating": 5,
          "text": "I decided to step out and try something new, so I grabbed tickets and went to LIV Nightclub Miami to listen to music, meet new people, and just have a good time and it definitely delivered.\n\nThe night was packed and completely sold out, which made the energy feel crazy in a good way. The music was jumping all night, the crowd was lively, and the vibe stayed fun and exciting from start to finish. I met new people, had some good drinks, and really enjoyed the atmosphere.\n\nThe highlight of the night was seeing Tiësto perform live. Seeing a big-time DJ in person was an amazing experience and honestly made the whole night worth it.\n\nI’ll be real tickets and drinks are definitely on the pricey side but the vibes, music, and overall experience made it worth taking the chance. If you’re looking for a high-energy club night with top-tier DJs and a packed crowd, this is a great spot to check out.",
          "relativeTime": "6 months ago"
        },
        {
          "author": "Rebeca Ferreira",
          "authorPhoto": "https://lh3.googleusercontent.com/a/ACg8ocKcglcL8wESfhdqt77hFopbDYhaj6LQ1Pu5pVuk_XIKkLTL1g=s128-c0x00000000-cc-rp-mo-ba4",
          "rating": 5,
          "text": "As a Miami Native, we know that LIV is the epitome of Miami nightlife. Fun, Elite, Wild, Clean, safe, and Bougie. Women are REQUIRED to wear heels so do some research before you go. Their concerts are always amazing, they host all the greats. It's interactive,  loud, and full of life. It can get crowded and you definitely should RSVP to ensure entrance (at your given time) and even save some $. Public Parking is also available to the left passed the next hotel.",
          "relativeTime": "5 months ago"
        }
      ]
    }
  },
  {
    "id": "e11even",
    "slug": "e11even-miami",
    "name": "E11EVEN Miami",
    "type": "club",
    "neighborhood": "Downtown",
    "address": "29 NE 11th St, Miami, FL 33132, USA",
    "lat": 25.7849684,
    "lng": -80.19355689999999,
    "hook": "24/7. The party literally never stops.",
    "description": "The only 24/7 ultraclub in Miami — part nightclub, part cabaret, part after-hours institution. Aerialists above the dance floor, surprise performances, and a crowd that shows up at 4 AM like it's 11 PM.",
    "rating": 3.7,
    "reviewCount": 2206,
    "coverMen": 40,
    "coverWomen": 20,
    "priceTier": 4,
    "avgSpend": 120,
    "openTime": "00:00",
    "closeTime": "24:00",
    "happyHourUntil": null,
    "musicGenres": [
      "hip_hop",
      "edm",
      "latin"
    ],
    "vibes": [
      "24 hours",
      "After-hours",
      "Performances",
      "Wild"
    ],
    "dressCode": "Stylish nightlife attire",
    "parking": "Lots nearby ($20–40)",
    "crowdLevel": "packed",
    "bestArrivalTime": "1:00 AM",
    "peakHours": "2 AM – 6 AM",
    "popularDrinks": [
      {
        "name": "Tito's bottle",
        "price": 500,
        "emoji": "🍾"
      },
      {
        "name": "11 Spritz",
        "price": 22,
        "emoji": "🥂"
      }
    ],
    "upcomingEvents": [],
    "emoji": "⚡️",
    "imageUrl": null,
    "instagramHandle": "11miami",
    "isTrending": true,
    "isOpenNow": true,
    "live": {
      "placeId": "ChIJZbR_3aO22YgROu6kdumheKA",
      "businessStatus": "OPERATIONAL",
      "googleMapsUri": "https://maps.google.com/?cid=11563170067363720762&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
      "weekdayText": [
        "Monday: Open 24 hours",
        "Tuesday: Open 24 hours",
        "Wednesday: Open 24 hours",
        "Thursday: Open 24 hours",
        "Friday: Open 24 hours",
        "Saturday: Open 24 hours",
        "Sunday: Open 24 hours"
      ],
      "photoRefs": [
        "places/ChIJZbR_3aO22YgROu6kdumheKA/photos/AaVGc3kMsFKMG2sdYoa2GtXPtqUMd-_uTTtl4lrO5DGhBjwW0oYvgOI2053IfxVnhinzv1mXbXGlWMSThO5OhfAjTDcTTrX6ByKA-vRH1yiYYKwK9KB_uy7XCvqqcAvB3DEgQlotPbCQORVXLQSYbUqL_WSA-WhpbHt_zyFJBvQWqxra9OxS1SBAkZKECey5Bj6CsBi8-9JsHTPMwbpDHumZmayNHP5RvTUZlkJIteriKKCi9F-716Iv33rstIZTYLmEpxoheoibUFyJlXlGFZTdGNW8YAmBe4Nb8s3WV85IV8XAsySbJawFeNNIXTrfpR2Tv1Cklvzi7rfOsVPgcNhBlLnKdPS_GF-TzGKd4Mz6-DSaXkdZ8dJGsTs8Zhp9Zy6xbTgIffpGd-UtnbJWL_GlqkFFLyEiEl5YHAjgYYKdMg2viQ",
        "places/ChIJZbR_3aO22YgROu6kdumheKA/photos/AaVGc3k_14GceSx1byfzza2o-JVu9lvfsqSLJVqAK3HSC_iHlyXqhdaBZYPN05iA0RYn-iENuHTA3UqEzf8dN9n050yJJc5ys1kvqGBejDaiXFTvJMmnnQTsA-6C57OxrPIiFQZzG3RkkzAKM9d7NGdT7Jin5RByot2DLoTo8BnJFEVxxID4NMp4KrFzuEKJgwgcFPM1NbDasQKwihXinVYRuLYL9H4cDeDgK1oNHl7h7BFRzK5C0y57vrpvy4IgOOKDyf7c1s4iixvzF_R64zBy2OlEGKi4VOlQgha8PueZiptOd43Ts5mUnt6AhhYDE46imW1Ax4jCaPUaAhxvQxgr9U-AHgBGBaGMyz7fNy_4zQfykSZI7Jx_qyFieTTiJ0vSj0v9VMoQVO4Hqcn7AF4kEmyFrRxuNOqvtAU8TvZbHiVk7A",
        "places/ChIJZbR_3aO22YgROu6kdumheKA/photos/AaVGc3kaIFQWtyM3p0dUwW9oBl1KpJfJfxsr1CCNTfRR9v9dd9znibr_9nClyKODG399v0tN28kT2_vkr-h7wo1UzWXazUngg-9p9t3HQebknek_TqdToabu_YTFdqPl4J1dlv9RzbeM_mnzBNdyWlUsxb8UoX1bsvf7FNTW8HME2OCW4kFEFnUsO8xMEqC25x3Nxj3sXNK1k1NyEagt00beYvYSqla5pQaUtTDpZEWfZha0hXFpNV_7q9Ks7xlRnHLHyehjcRvhYCQK6wnk_YyenkkbmqwfD8gXjdA-ZRZDwQgg3ftq79e6WZDy3Ku7xFDDudilmFfqOlBex-MW1bVkSerhcMJOhpCDxui3vuHBGkqilie7uTzGN_hrt5f0wTYn_CjtMAszND1bOHmXdSJp6bFxPRqER5EhwJmhdDVyBNEGXT7cIdWbQEmnJo_55wPq",
        "places/ChIJZbR_3aO22YgROu6kdumheKA/photos/AaVGc3moQ0bQGCzds-jq6Bj8JRA3PBm42Ma2V8K9_dKI12yHiP5CoYL5S_lDY3hEPnnpT0A4RkhiUy71Ko40kCjtph3WLdMyCCvvizaiYi3uq3_kSrwnsxhkQlaApaJ5qdCXLj_iS8goBHdjt3G_R1W7_KE29fv8KlGCYolAFWID_QHS0hKCE8bc9Wmz-fWIy4F1vkMTo2tDchDv0d3rRbxAQNyxcuwgVkMM2bWbrHoa1-rTG7NT03RWzmHpPt9bOQDdalqOEzf2YrGFEPWpx7iH3VgzywJxAzvy6Qo9DIDO3eCbJgnmgo2nm9KkWATbwZjpOJZL3i0J921ZHtnTQ8Q9UR4WGK6wgeGx3xNEPLYPwPmDNLb1sDOQv6MSKSlpCU7-RY2yCC65L7xA1GWL6EmWOJHp8V0A6c7vQz2tCrMA4clnfmKM_3l75BVlneqM7g",
        "places/ChIJZbR_3aO22YgROu6kdumheKA/photos/AaVGc3nS0qBuInLqjmLgpjjgLdAHavPSK__oFxvggFloLobY7_GwAARBFpPQeIPOyoy3LzxrwWeXUBJ3d61pmG7FI7kHYdbVVcps7YwdmfxxdbYcyekoI8IINilG-8iHXOsR125j-liec-64s54BI6lUJNNRibfRz1NtvJXO0tKNdjNs1Y3gcYfF00FdLnOR1boluGcW73je01L1qI6od_Ydtw4TD63o1pU7BNjHYE6_WO1RpC0iDSaeEYfXXuYtUunn4dpR1KuV0_7ZCqQ2Gq-ILFH96OSynOH9b9bcme9eLbKxUzNx8dIhONa8upGD_0LntMohKVk7s8lrXU3t3xhUwVxRnOMWbuP1YQsy8kAJ15eajLhQAsmPfCrMz95YRC0nnHrutNdB6EUBVk9ztkzluMsz9kabNOBOVk44yhIbzn3Tf-6ZuhYrv-K0ubpshw",
        "places/ChIJZbR_3aO22YgROu6kdumheKA/photos/AaVGc3lJ4P999iDuZHXBYlTT323DH2pQHWcLYslU0HFU4LVox8Fi3078yJAlWk16l-ElOlCjtslEd4QZMCIbzZkiBzYV24UTtqTehOAO8qG07I36DuRpgAUflseWzNKzBz8Rowr0k5zBWyR90eym9DR1JlRQELCRhRIR-mM6ANyrxYUK9z0IOFpC_-xrKLPz2AsIjZZahQc5I5uv5fUOFbEg6b04w9Il_13FIj_KCv1ei-yYRyQ2ISFWECo-AdHRvOPL09-IY8u_A8HcXKwxe9Br27Gixom6HjfZ4r4KnOxrGGp_G_FDR2H-l1T9T5DP2sB2S2t04vhj8d9rnYOkqwefqhOI_xe5Fmw3TwixgrZtPoB-achJK85R2jbfPrwYuAfhGN75MzyEXK5Y2UPTIX3_y6YW2PrJVBq6tIeIr9ltUbcd_14ziu_oaQ91_uF0aRqF",
        "places/ChIJZbR_3aO22YgROu6kdumheKA/photos/AaVGc3los5P6HXWW_F5phYFWcUTMIONVSaXjpbkisVlGcpx1omA3NezA9xiK6B_z6RRJcjV3Sh5DvUEjom8Gjajxp4tA-Lr3sLZ6VQvozQAGtub8J8vB2L4CqqiIy-diDmzDFyWbNLAnCjnAUOnrV7H8Hu8UKtHxlxRgi6023UkE2ItfgXZPY0CSIjJK0joHFy1Wc2wSUiGwFPRmOfU1F4qlwi-V1HYljh1WPIAJ5F-BACOJJJHe7lxQMDHDaY2SWR3yuJ0dyuABrqkNRggL-Xu0QxD8POODl-bptrP6x4_wGkWEbYbQYn1S6vUqiJRYhkBNqNza1A7S_dvA3-k9lKhrwg6mgrgp07O3Y3kWdKr11eTyea6lGQrqUkH4DoaqAexcF5_7YnrWS5sMNIv7bpf7PqCsXyJ4e9ok0-Zi_pEee-pgOqWN",
        "places/ChIJZbR_3aO22YgROu6kdumheKA/photos/AaVGc3kUeB2bNdRdAo-AzPCmaz2PlujFLbk4eTXRoflTcRytOryHnvzpcLAP1yghMceHAnJKvEe9Afj3DLnobJulntJY5DnkJf9TzRgLqLrOspEtf8YoK80Btsg08FkHaaNJI6t19LKdmyIYZbzSpu9fbuOiKUaCxwpdYI7tlp1InerrGLKZvKTVI8pkezD-em24JMO1tPt6sdgJ7UGImslflx5bPsWf5wbji8RKZGU5TD9wTAGv_QJJZkH-7pRDpo1g1l70YS1iZq-IbeEQVACciULCriWnOq8N3ETsyaShCzdthaW5IzERme6vTZNMgmWw7n6Cbk8vhTGbkANSTpeoM_VkURfm5gdq5SosDUM9kz83QT6yG5SUWpZgKO0XgY7-SZT4xCy7qdjHM1HYdnLP2kxnctncvWVADa268y5taLZnPxvuI2factbag7bGIQ4c",
        "places/ChIJZbR_3aO22YgROu6kdumheKA/photos/AaVGc3mV5DPNYPsyrqRq-NPWC1Tij9ooQkZBBNTVzwFtGLtRSQKCh4iAQlU5hBwQOJYuIaKVc2EbugBaBoyWR2ROn-chOvrIZV5xDibhQV66pvY6DhKBdU5e_pt9ySgNnURWMjCCshHHOO8cX2XdycZLRfhncee734qH0jlp7zpWBGYAp0IRkc6gqCSac30L6hC-dL-aAcpOdv0RJuZ14LaxqNeaMxJaIleda0JvqDX6vB5_7aebrYL0QPN1uYsC_6GX8u98XWzuNXlvuOcXQwrtFn_iR-S5UnszMJcdk4SzHNFt2dQg7kR8tvAmyzGAKm99TCVLiz5mCut6ymVDaWGv3Ps_VyE9ABVi2eLQkoxNMWD6bfSeEbFJKqg2We_yKVHvtwXrQX3a3QwQAxIpBJRCFMn3LhjxcfoyPce03WcFmWymDQ",
        "places/ChIJZbR_3aO22YgROu6kdumheKA/photos/AaVGc3mjSIsDlyMWWr-XJODnxP-nygDmK1_mZWHztbyX13ziDzgEcyLVQHPUHWFOsAXiVs16xphdx3Sj0snKjGubJ2tD4IfD7SMO2CdWuoIn2GRU-Xfo4Oj05eSkx60AqLj9dGNlX7qZjP0ovTNaJCQIa4NauQui2cvX-Rqx38CwUABnsWj1DccNFUWLRIk0ajQ8tILcqQig-iMZ0G-AnicW4_6FyGOWtigVId7fAB40K1Cz-QeIfcBVjbNpZE4C2OpQavCq5M8rBMK5Mge6QrZ9gAWgR8BCNT7_w4o7rMwEa6SD5_cPzdaQEAKrhelKUW3-EuNhiZrBaKllhG-cjaoQswUETWD-8xQqNnOCWhiE2eEg_noLfs0HF7WL4Dxcq4nBTkqk9EEPTWw1ri0OdE4yGcK48p8YyPh41A3cO0YvON__hdJE8iW7yMNaUxNeUehj"
      ],
      "lastVerified": "2026-07-06T20:07:01.604Z",
      "editorialSummary": "Energetic, neon-lit night spot with trapeze dancers, burlesque shows, DJs & live music performances.",
      "primaryType": "Night Club",
      "priceLevel": "PRICE_LEVEL_EXPENSIVE",
      "phone": "(305) 829-2911",
      "website": "https://www.11miami.com/",
      "amenities": {
        "reservable": true,
        "outdoorSeating": false,
        "liveMusic": true,
        "goodForGroups": true,
        "servesCocktails": true,
        "servesBeer": true,
        "servesWine": true,
        "restroom": true,
        "wheelchairAccessible": true
      },
      "reviews": [
        {
          "author": "Liam BM",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjUvZbAAOXHaTnzqiRDdKFlUJaBOh7nRm-DJV0KPS3FCKHiIuGm4=s128-c0x00000000-cc-rp-mo-ba3",
          "rating": 5,
          "text": "We went out last night to celebrate and the energy in the place was unreal from the moment we walked in. Security was organized and professional, and even though it was extremely busy, the entrance process was surprisingly smooth for such a big holiday night.\n\nWhat really made the night unforgettable was the lineup of celebrity appearances — 50 Cent was there, and later on G Herbo and Meek Mill also showed up, which completely took the night to another level. The crowd reaction, music, and overall atmosphere felt more like a major event than just a regular night out.\n\nThe venue itself was packed with people but still well-run. The staff kept things moving, the bar service was fast, and the place stayed impressively clean considering how full it was. There were a lot of performers, all very professional, and the overall presentation, lighting, and sound system made the whole club feel high-end and exciting.\n\nWe were there as a couple and even treated my girlfriend to a lap dance, which she actually enjoyed — it felt fun, respectful, and well-managed, not awkward or uncomfortable. That alone says a lot about how the staff and performers carry themselves.\n\nOverall, Club Eleven felt like the place to be in Miami for New Year’s Eve. Between the celebrity appearances, the music, the crowd, and how well everything was run, it was an amazing way to ring in the new year. Definitely one of the best nightlife experiences we’ve had in Miami, and I would absolutely go back again.",
          "relativeTime": "6 months ago"
        },
        {
          "author": "Edgar Viloria",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjVrvsWEg5P5qnu9WiS7dKRUl33lQZb_N7aoeIJivMATyGwu3HZj=s128-c0x00000000-cc-rp-mo",
          "rating": 5,
          "text": "Truly an amazing experience! Friends of mine recommended this venue to see a performance and we ended up going on Swim Week Miami. We all from Dallas, TX so Friday night we got to watch Rick Ross and he didn’t perform until 3am but the wait was fine since your surrounded by beautiful woman, kind staff and the patrons were just as kind. I got to meet people from all walks of life which was wild. Bumped into celebrities, locals and a bunch of music lovers. The dancers were so talented!!! They put on acts that were mind blowing. From spinning rings, high ropes to death defying stunts. I couldn’t believe we got all this in one night. Drink prices vary but are reasonable beer for $8-$10 drinks $10-$$$ depending what your into. We didn’t get a section either time we went but our 2nd night returning that same weekend we went to see my friend’s wife DJ crush Sommer Ray and when I tell you we got front row for her whole set got to vibe and chill with her and she was so sweet. She even finished off her set with a TX anthem which made us feel even more included. No other venue let you experience artist like this. It was to the point we are already planning to make a larger trip to come back just so more of our friends can experience this. Thank you for the amazing time and treating us with such kindness. We will absolutely see you soon.",
          "relativeTime": "a month ago"
        },
        {
          "author": "Christopher Hooper (BLUERAVENstudios)",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjUexcrl9c3cYuO9njg9c4p4UoaaNgtW9sSfQSAiTzwPaXx0OZng=s128-c0x00000000-cc-rp-mo-ba8",
          "rating": 5,
          "text": "E11EVEN Miami – Miami, FL\n\n⭐⭐⭐⭐⭐\n\nStepping into E11EVEN Miami after its recent renovation is like entering another dimension. I had the opportunity to be invited in and experience the space firsthand, and “next level” doesn’t even begin to cover it. This place is operating on a completely different frequency.\n\nThe upgrades are absolutely unreal. The sound system hits with crystal clarity and power, and the lighting and visual production are on another planet—perfectly synchronized, immersive, and constantly evolving. Every inch of the venue feels intentional, designed to create an experience rather than just a night out. It’s high-energy, high-tech, and flawlessly executed.\n\nWhat stands out most is how everything comes together—the music, the visuals, the atmosphere—it’s not just a club, it’s a full sensory experience. You can tell there’s serious vision and attention to detail behind what’s happening here.\n\nI grabbed some incredible shots while I was there—definitely check them out to get a glimpse of what this place is all about. And as always, follow along for more experiences like this one.",
          "relativeTime": "3 months ago"
        }
      ]
    }
  },
  {
    "id": "space-miami",
    "slug": "space-miami",
    "name": "Club Space",
    "type": "club",
    "neighborhood": "Downtown",
    "address": "34 NE 11th St, Miami, FL 33132, USA",
    "lat": 25.784654600000003,
    "lng": -80.1931826,
    "hook": "Sunrise sets on the Terrace. A rite of passage.",
    "description": "Miami's temple of techno and house. The legendary Terrace stays open past sunrise — marathon sets from the world's best selectors, a crowd that's there for the music, and mornings you'll never forget.",
    "rating": 3.8,
    "reviewCount": 2418,
    "coverMen": 30,
    "coverWomen": 30,
    "priceTier": 3,
    "avgSpend": 90,
    "openTime": "23:00",
    "closeTime": "12:00",
    "happyHourUntil": null,
    "musicGenres": [
      "techno",
      "house"
    ],
    "vibes": [
      "Underground",
      "Sunrise",
      "Music first",
      "Marathon sets"
    ],
    "dressCode": "Come as you are",
    "parking": "Street + lots ($15–30)",
    "crowdLevel": "busy",
    "bestArrivalTime": "2:00 AM",
    "peakHours": "4 AM – 9 AM",
    "popularDrinks": [
      {
        "name": "Vodka Red Bull",
        "price": 18,
        "emoji": "🥤"
      },
      {
        "name": "Water (you'll need it)",
        "price": 6,
        "emoji": "💧"
      }
    ],
    "upcomingEvents": [],
    "emoji": "🛸",
    "imageUrl": null,
    "instagramHandle": "clubspacemiami",
    "isTrending": false,
    "isOpenNow": false,
    "live": {
      "placeId": "ChIJK69z3qO22YgROBJC2vDIXAI",
      "businessStatus": "OPERATIONAL",
      "googleMapsUri": "https://maps.google.com/?cid=170231822712705592&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
      "weekdayText": [
        "Monday: Closed",
        "Tuesday: Closed",
        "Wednesday: Closed",
        "Thursday: Closed",
        "Friday: 11:00 PM – 11:00 AM",
        "Saturday: 11:00 PM – 11:00 AM",
        "Sunday: 11:00 PM – 11:00 AM"
      ],
      "photoRefs": [
        "places/ChIJK69z3qO22YgROBJC2vDIXAI/photos/AaVGc3n7GNYVy4nbHOaqBMlay5j1svQvD95eZ2Y-ggfg8Y6LfYueumiHXF_SjLZEnLMmHydnZtJ4ABu5h48DpbEq_ALw5GUE9BIvtDShIoNkv5xeH-TD3Ge8nyr1PTPdDAZxE4hg_hcgco0qR8-61QpVC6hTJ977nEfgr-2nTGWBnxt3ifOt_KKmLBFkgBTPmBOQVYxVIjkfXLolqx0ie2uoKLjy5QQswfBt8u03J19c7MF30KPlcJafrIRV6Wm-72YX8XWDDSuiXi3WrOByQrmvr1NhMJviTcDi_9zJsARurMQQRQGAPBs4mhdkxW96Rlbd8hbXLeUaMk1wUhXDvZMnMXE6Ao8e0bqaEZ2G45EPEpRqiUHHjIT5uKnMSBkJTHGg65ewj-QPhBJJQr1-xLcflAKH6mcP3cHkojAAqgmezXF2oLI",
        "places/ChIJK69z3qO22YgROBJC2vDIXAI/photos/AaVGc3n93A-LvTMpcSTzZ3BpqaiDlOj2YqoL_kz9-kLl5RvxEzT2MhTG7gDN_OKV_b08NwoYQUuDyo_Hfu1fUJozriUBS3Kfcu76ngPuwaBhSlPw6NBhiiTWKDPN8b7eYjV9evyhfZCqQ_z4MiV6b4SMj93JhQ1woDB0xnwcCQ8bDQQFcV9hxxeHj4kZIyHsXfuJhpckbD3s6iX2z4UxwGysGDiKy-bEkm4NLdbZ9rfXuXMHSSWj7MEDIaWCrFH0QM0Y5F8ozk8VoqLW7AIP0hlzph6izazGj5jOjWDNk_Bdqkmb1nq6tnIDLaGzdb0yyQtl12fMC0X-2IwfOb6QbSlsyUcNz17R6ak7M9GhojfOt2lj5yruu0rZJJsRj8wC5_ahmYUJAxDdwB67Zn7ADlfujP8QPMXSbX75uauBFI7w6WEZMlOgXhZRrOo-nDU3pZ9F",
        "places/ChIJK69z3qO22YgROBJC2vDIXAI/photos/AaVGc3mANxala80p-49nKLBoD_wOZwR4RUI3bRJ-YsAV-iLavLLd448TNE3bz9KRQ5CrIUKD06TrSu6hVnL539WNpVNS-9qM0NWG53KLchHozEegKFoaAZ-IZeEftzNktpQgdF5gmYp4E5_rU_9IJuq1-fxdXVyVu3Ds_Xk9NRNZPUvmYMDAAxDfVdw5DAWdhH0LpgsAAWSw7_IM_cdLOtETDVPceqLdMJ3iMfGbHnRP_S6BDaBiGhZMjhIjDkaAV7TEJ_2Cf0ZFGzXtODtw_vPmQtEKv2atzhcUDJl8MXB9_XQ-Wevw6ErrezjL18dmSlplCN85_qOgKarMnvHCyN5nj9ppN6ZaSX0ZmQ_cv67dmy_5sg0HXeMPYHuSzYCMjvS6kWZClfOcYU3SVBobKRXtELrr4PMhohGt4sN7Lztw_pZWRF7Ma9skn4XZQCSMwli6",
        "places/ChIJK69z3qO22YgROBJC2vDIXAI/photos/AaVGc3mmHq2kxEbX2drsz3wEN1rVCg0nnv5ELLENnNnvS2mvtj3Hk0EqFn3VRTuihfcuwvjmUZZV-Dgdgcit9bErdNprWqSFZVpqWppRJyATHtSqZnKmSDcvBIuQ31-rr5LfUF6nUHccBayy69Srx4os2gJgaz0MneEt1IE1K0rIdzCPN6jVrIYxcoHPh0AliRJnVBT5iqztE9goSQdaiPN8DlLZ5AgIbXjKAlPW6HLknuZ-v1Sw42qmMG--ugmFeegU6RQFJoKD_pUc7nYxO-5HDhGOtAk3Q4xbujQlV8oSyPtZ-YGOqN8Sq_Nmxf7HWVnYmfqzOSl0CI3GpcESHv8i_FL6-lk6SyZtn2YaDXf0Yi6yfX4ub7GEnSedDn_B-CAA7Mxt0SH2v7kur8U5W_a_eaTceHNARXHnwNZVynxDiNmGif0",
        "places/ChIJK69z3qO22YgROBJC2vDIXAI/photos/AaVGc3lj9ViiF9Ktbc4p90wFgeFahUJGcP1l0pYJ0F8n-M5bJFpuD-ARpfQkSZ15bV3w9Wd-OFPAvbeUlJbrgATfOTh49qItA-hcYmj7NMosyBqB6FOw6n3EP5BIZBngvfzYRpiCw7wIf7_iElI3g5AuvkJMjDgZXLxIJxK3p65eAfXTIFeRaTCxjtpLLk60iSVbEajPLBjiRFJbIIWOiZ7MW0tUBBX9XjGjz5JVZY1QmZEEHM52eFzDeFifl7CvC6P9SmrA6Wc5aDRcl6d1G-RGuidw0w1IspSFMXe0W9OlEWsVeGIUHcJVKMp8JwJVV8HMNt-897TQoB05JUCJjP6HUqKKsfApCn2ufdMp4DsVUVbmwrVq7a1U7h9PgD56NW_NgDVn7pF8Ki8VTpAVsrMJI1gRM8aH5TVAwvBkoqSqRRHZu1xW",
        "places/ChIJK69z3qO22YgROBJC2vDIXAI/photos/AaVGc3nbJ-MHNV7j9iZnsNH09ib9zJhVlpheFEs2bNFGvJhN8KjV5qu6o9fdFLkIwkKdGDNFbMu_4dHIxAAO3xeMAVZz5gvCrRUAqYG8aaw5wMp3_6nrRT1spYUNemI7kEFhPMcH4Yge_seE_YaWWC0MqWTNd5BQAkyZiOvqxBUPrWBV60uk9cuYE3EqOCRcHbBQswi8BFF1Qbl3dHHl259d6fa28_bjwguo4jhefP03QQCcakvg7tdsM1yI0mN6k0Y0h6XuROONL6Xz5oZK25Z4smsM1dKkW7EHNGCJsmJRwfMdMSrsQ3HHzXJRKwEujNHnNJjP36q5XB5vRkWImDsl5duvhl11yYBChcEB3Ebv4Q9zQoC4IPJoQ7j9JafeAKIRsABswn7iEVeCnjA8ry7Q1FIt49v1ORzolEJA1zLzY1M0MA",
        "places/ChIJK69z3qO22YgROBJC2vDIXAI/photos/AaVGc3ktmvzVkkXRoa4iTINYSosSfRy8oxrhmzk6MyYoT4QWsDJWmocothpuzs8asbi_6d43KBFgn4We9WvZoGL7xWb4NT1Jv9ubtW_SGa5OE2BLY9Yqf00IZBB3FfK7VOeSohM9A_TvUPAJo-GqdchR3cKlJeDkSGV8YsUriJ6BXktp2XK0HzUgoDbFa37beIzihqUj7LmuLmaRtPd6kBsS-iA-J4JsntwW5nocWsxLLe1NMyq5L9FsYShLPIKyMtXhVLiUulXOgyn6rZXNjlxs2u6XnVJxmo4dARlLVgljBLW8EjEa8UiYyYJDsuJEjjprWBuft6V7TJYut8dM4k-DcArgeQyNHWBaFX8fo-RJf90yYuLvKooSnCM4-uoxsF5GqMcAmuFRh1q2P_IiwYTHXLgawV7teWS2H3goXcLHgmkzDQ",
        "places/ChIJK69z3qO22YgROBJC2vDIXAI/photos/AaVGc3mYKa8pz87G9c98AGWYvWd20qw9olcgNZgZJzPnCfKAV5Rd8RDQCTUk2IjZzrzNjMSTmMcX-QwUuP-6hlOuvFTKjMD0IKi_EedMGmIEsmDQVlNPXuafWfj2KkU1AkwoVFk7_-O7a_E8vymtbTq8x2_mGXGwvRuxNHoAWtIET6YUareKp12E6lGIEwvOgZqSBGsBKwHUSD9vvlwBOqwd1Yzi4RYQ6ypuz2KIOcjP20SCLCJ0PAheXEsueke1BlM5gpcusZ93Y2PxslN-2D4qIATMs0oYYcczrKqQvZ_2Cia41Wesw_3gG-VJJwUqG9xwtF9rAysfUAdCyYxVnEOpm-CuPZ8xrwZN7Qy8ENxdnLF7iMntKgprxZvA8fDaY8J7y17Vx3mlfQTroJDdHWVkr6rr67N7cakSfrjnfq4ey4CJUqjuZUokap6WwWYry0ze",
        "places/ChIJK69z3qO22YgROBJC2vDIXAI/photos/AaVGc3krAVlYYm_7SjqJFmrFlPd6Gws3O9LAPpVpXSiK_9mQOZXti7-CX0LtwzaHn2v-n9lyf0Y3NmBbZclQQDNCoyldsePfwFqYhokTD18-kUGtZpY6MSJnbruWqYqNaJCMDwllMvJrCDz81bAL7U7KJaeWjY_gHPfpW7Js4MG5Q4UWmYcc1IzKL7A2vjd25MbLhyL6mLI0wnYwGaM8zs5dctib7fqIaozzAusJ_TQ1GrSPGrgZyJf4GCE1HcjzfiPZi-ssiURCekPNmO6YngRdOI-by_QTvYX90Vy_b52Hszj1iQafPEC0De4mcpO6BFiSIsBuU6boxJf0gxTCnzNxx1aZlJOl33kJNpm91i5JsMOzrKK2Qfiud1q3pD_qHvGQTha94j7X87DWNeTUV6QoLDcazwc5JRwSNHAR-gnKb6VGiDst",
        "places/ChIJK69z3qO22YgROBJC2vDIXAI/photos/AaVGc3l-BcoKTOhLZ7Q5O7lZy59VlAJl-8IHMKTIgNWrzCAvB7UaaU0Onl0fRZhD8QIiBRyLuO9C9L-WW2yoHY69mPJcvdKndfn8J0tCtLDEBorced97Y01C8VTc9p8cKB207BW5gP3YmeEG5nGBv5RyPjEaEZ4slY7kD3IG4FAniU_eBvE9SeW9w3ObUb4Wbsw-Rvx_Ps0PvBtikmTnnh0qCeGAb98dn-4lRgMY_y0S9CkigaltSM4A9wA36QRLFleOgud5p1r46M6Li2DAIs2KFWUqgunzbNlrUFrLdV1KagojFpMTDAvYOJuCTX1Dizymjaw8MiqC0unJ8mQ4GtjYOf9lbx9Yuj0U_F0OiCNx9XEgGHFx5LplV3l-WVLkO9sYe0WFbd4NBQSMaJW2oVNF25VROGn6GkKjPHec5StTfr0wqA"
      ],
      "lastVerified": "2026-07-06T20:07:02.183Z",
      "editorialSummary": "Famous DJs spin tunes until early morning in this trendy, happening club with a rooftop terrace.",
      "primaryType": "Night Club",
      "priceLevel": "PRICE_LEVEL_EXPENSIVE",
      "phone": "(702) 738-1333",
      "website": "http://clubspace.com/",
      "amenities": {
        "reservable": true,
        "outdoorSeating": false,
        "liveMusic": true,
        "goodForGroups": true,
        "servesCocktails": true,
        "servesBeer": true,
        "servesWine": true,
        "restroom": true,
        "wheelchairAccessible": true
      },
      "reviews": [
        {
          "author": "Keilin Perez",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjULL6wx6CFb5bAeYrrQjyAIGh8AXvWJQ1pbo0V5Ml5Lq6SS9Gqj_g=s128-c0x00000000-cc-rp-mo-ba4",
          "rating": 5,
          "text": "Club Space is not just a club — it’s a Miami institution. The energy is electric from the moment you walk in, especially during live DJ sets where the music takes over your whole body. Deep house, techno, and nonstop beats that make you forget the time completely.\n\nThe crowd is a perfect mix of locals, music lovers, and people who came specifically for the vibe — everyone there is genuinely there for the music. The lights are minimal, the sound system is insane, and the atmosphere feels raw, immersive, and euphoric.\n\nOne of the best parts….The outdoor terrace. Dancing under the open sky while the DJ is still going hard is an experience on its own — it feels like a festival hidden in the city. You lose track of hours in the best way possible.\n\n✨ Fun, wild, unforgettable.\n🔥 Perfect if you love music more than posing.\n🕺 A must-do Miami experience.",
          "relativeTime": "5 months ago"
        },
        {
          "author": "Robert Pocasangre",
          "authorPhoto": "https://lh3.googleusercontent.com/a/ACg8ocKaVZlMpOigvzd6liRXe3pKP3QbUd320JSy2avy6nJi1nO8Dg=s128-c0x00000000-cc-rp-mo-ba5",
          "rating": 5,
          "text": "If you're coming here then you know what to expect, world class DJ's playing non-stop for hours upon hours. Get an espresso martini and the delicious grilled cheese. Be prepared for a packed dance floor most nights especially if its a big name playing. Drinks get pricey quick and if you go last minute be prepared to pay extra at the door. Highly recommend planning ahead and don't get to the club too early. Most headliners start much later in the night/early morning, think 4am to 8am. So arriving early at 11 might get you a cheaper ticket but you're going to be tired by the time the main event starts. Arrive with good vibes and have fun. You never know who you're going to run into or what exciting stories you will have after a night at Club Space. Good luck",
          "relativeTime": "6 months ago"
        },
        {
          "author": "Melissa Walters Hoevenaar",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjUIGe340PNxSXwv7S5tmD3WPoUabtBsMvtKFkrLhuG_mwmfJKta5g=s128-c0x00000000-cc-rp-mo-ba5",
          "rating": 5,
          "text": "This is the closest to studio 54 you can get! I was impressed by the Security when we first arrived. The line went very quickly. There are plenty of security guards all throughout the club making you feel safe. The music was fabulous. You could really feel it. I went to see Adam Beyer! The club really supported his sound. The bathroom lines are long but they go pretty quickly. We departed the club around 11 AM and the staff was still fresh always willing to help.\nI give this a 10 out of 10 and if I lived in Miami, I would probably be there every weekend. Treat yourself to a legend and get there quickly.",
          "relativeTime": "5 months ago"
        }
      ]
    }
  },
  {
    "id": "sugar",
    "slug": "sugar-rooftop",
    "name": "Sugar",
    "type": "rooftop",
    "neighborhood": "Brickell",
    "address": "788 Brickell Plaza Apt 40, Miami, FL 33131, USA",
    "lat": 25.766635299999997,
    "lng": -80.1925061,
    "hook": "40 floors up. The best sunset in Brickell.",
    "description": "An open-air garden bar on the 40th floor of EAST Miami. Lush greenery, Asian-inspired cocktails and small plates, and a 360° view that turns golden at sunset. Arrive before 7 PM or expect a line.",
    "rating": 4.2,
    "reviewCount": 3758,
    "coverMen": null,
    "coverWomen": null,
    "priceTier": 3,
    "avgSpend": 70,
    "openTime": "16:00",
    "closeTime": "01:00",
    "happyHourUntil": "20:00",
    "musicGenres": [
      "house",
      "pop"
    ],
    "vibes": [
      "Sunset",
      "Views",
      "Date night",
      "Garden"
    ],
    "dressCode": "Smart casual",
    "parking": "Valet at EAST ($25)",
    "crowdLevel": "busy",
    "bestArrivalTime": "6:00 PM",
    "peakHours": "7 PM – 10 PM",
    "popularDrinks": [
      {
        "name": "Sugar Colada",
        "price": 19,
        "emoji": "🍹"
      },
      {
        "name": "Yuzu Margarita",
        "price": 18,
        "emoji": "🍸"
      }
    ],
    "upcomingEvents": [],
    "emoji": "🌇",
    "imageUrl": null,
    "instagramHandle": "sugareastmiami",
    "isTrending": true,
    "isOpenNow": true,
    "live": {
      "placeId": "ChIJtwclboO22YgRoEae3LsRNio",
      "businessStatus": "OPERATIONAL",
      "googleMapsUri": "https://maps.google.com/?cid=3041638096893265568&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
      "weekdayText": [
        "Monday: 4:00 PM – 2:00 AM",
        "Tuesday: 4:00 PM – 2:00 AM",
        "Wednesday: 4:00 PM – 2:00 AM",
        "Thursday: 4:00 PM – 3:00 AM",
        "Friday: 4:00 PM – 3:00 AM",
        "Saturday: 4:00 PM – 3:00 AM",
        "Sunday: 4:00 PM – 2:00 AM"
      ],
      "photoRefs": [
        "places/ChIJtwclboO22YgRoEae3LsRNio/photos/AaVGc3lkGw1tTL2U2rdiJqYI-JVh9JEQDWHfQ7R7vCY1MPAdFrKBUBK9T_VA25mn_zpNCKkkBDJH038pJYLGAJCTymEReMwEOLLVP8Z-XMJK8IKMOlpz9hw8X4KUejE7FBRZ_PrT9gwbAxTAddD_L3XZZLsgNT7UjYlxEE6ok7Zn1I0gwUVjebdXytENCgvB6R3xKNVdGitY3oS1d4Yu0V9oLH3VUPCYNvrfVFupqVuBF_9h_-kB6SWu-2xl_Shl4TkJmVISjw7sLq7BE2xnFIQtgJAMV27ahNEfQ5Gxz0oOxTFz-cV6lgNVqH44L4DFWGluJKTD_h6nv0uE16F1OYXCnt-NR4mFCKmGn4KG-VXJwWgj19w1liCTntFmPrsBUKeHph5HCiFe1xZE9vKLg3Bhv8LZJoY8KjrU1Ac6RA3XFC6tTUfz",
        "places/ChIJtwclboO22YgRoEae3LsRNio/photos/AaVGc3kbcWa_59EeSPjGpDrw_GXk3AO7j7-n-Z5MhzZS6YAb5wHAzVnm121n62FhX17Zu9UfaZjWskT6X2apDvCaS1jXoUSESDlnuOPwgLa3M3zJZnVtFPPdxGqYHTS2ePtO8bgi7g7ToCNtcnUei4y6K1KPjCDVUYna-Tt-XkrgXj8_H0617OVy6mwAohXSDWJEdAcOHclpc2T4xCx4IZVTn86oY3oU6QwbbwBGdI9Wb-tevzZsDKO18U0XWvCalFcur4EK-IVQ3o3_ZxiAwJA8GOn0Kw9dd00Gp0OlNw_daAYeM2opdzAtT1QAikRHTpnpZgvGiTyhUVvjYZIfAIFolRsBIOZGKTrG7VpG9yZXmG4oyGGDCLiYS-meXVWRVnyz3V2os_Mhxi8u9PZWYws84Elmdyyt_Dfeepmtfm-Oj91WaYjX21dgbJEKDiWWdQNP",
        "places/ChIJtwclboO22YgRoEae3LsRNio/photos/AaVGc3m-fayrJo44_JaMYgRVWjoah5l2afFsa6MPjCqBjdG25VsSzTfK1kG66_gpaxgv5IReRKOjeIj9ZO6gl_4v36oh76K_k5a6UFqA1REKgbCUJ-wRtJCr3pb3nihcj5vlWQYNCs11NzSk9VK_sJ5mQ8_JA6fZ2GajKH5G8cOQkPNqPw9rS-8T9raR2lvYusnNaO-jr4E1zXVZ2Tk47u-_nFl5x1Fqw0jZMzsozDnZD3YQunLJow5BWVPOg9ZuG9HlGm5P0szykk76DzqgzbJcVFTZoYqgckGeac1h2uAK-O--ksbh4xJHfIEx9ZhZ-OZLKXmlS0tQapjVYDCwgTVaSxHdX7GU3jtUA3PXh1iMUGczGZ9WjhNgZORBUaFugCuabqPFqTq7jgHIHS-kyRedcp93wlkUeJK6jFDLgDVbSu2tQxq_VNbHymdkowriIpo4",
        "places/ChIJtwclboO22YgRoEae3LsRNio/photos/AaVGc3nM2-aDao7RrhdKySknPvCgpVXB7ab8Tx1C3D_femdgarM-1RASYPo3JCcVclROaAtBBIwB3lWmnaPm4_-g5jUV5h7RcMnGVebyVqGEv1pCHlmdkKMpWkBO1kX3Dm45T9e5vBOVaQ8Dx4bH2QjD_rtg4G9HCUsrneA5CEkvDAQiU52B8wVxTD3-BjrGzajUoGKVCubOAPiLdH0C09uhvdbZP3xEY6Dzim3DNzAkOICMUab0Qwiu9FGBd2TwY082IZfZHepc1tRD5XFFCiY2DnxHJEHpI02YKuCLy2QPGh3HA1RnyfcfzbqConi6X6mN_MKZJYYVUi4s78b_myCVCLeDAKALFiMfphA1Bh1CbZAyLviW2s76wtMKNOV3sc06hiJGd9QULTZvFOcxR46VbT0Uoiz1c6BpdwTqw_n6EiLoe3_cicV5vvXD2I5qMMgN",
        "places/ChIJtwclboO22YgRoEae3LsRNio/photos/AaVGc3ky-Xx-S9PL4M4DnsUkO29Vj_UJN7xVde0c5cjRPDhcLSBydNfZkB7GzTa5DjricEO1MBAixpIth5zsKIeVe63VxkLNha3-4IeieYVwTvFfFaALiqVn_iVl19f3d28ncrVzc_fCiwe-w1KB2hyCkKmAOkk4qzitGaEQVqkJaSUclY5-WUmhOKWcbpmOPLghqI66Umh19I15tCr-XeNR4GsYwxH8S8TJ59IAPUGxiDkqSDeFbM8mdJAcuecO0KZclvG9GmMc9_zb-8Kg_LQ3f9gGY2Hyz5oeehfx4g7rK4rJyNpss3Q1rfBt6Xr6qQ72jFBLCVu-mRgVOCsW5oHJY6HSeGvj9HSG6nDNvNH0xjEBqdfKoi4lqfITEDAWABv8_LRHMi_7NL9D0Vthr4BQfYOrad5HeUXNn5ovz58eo4dIALPnJ2eQ06nUuzEjPYZQ",
        "places/ChIJtwclboO22YgRoEae3LsRNio/photos/AaVGc3nOe1hCDGvTZQhoYuUCVu2Hl2IURS3dKuefXSQXTXFT4d0VQ_vLzOr6eIS1s5bYTDnLnPnBfyz99esh_9T3jo9GEU7SGzbLttEZOWemi7t0T7AWIPvW6BEflehMu8uejyikfSAbn2PxvCQg1Uc3JhvhO2Why-RImeQjdKpmF24lquy8G8DspQD5Qz0CXj9TOVvIFnEUpY1Q8B6O90Lj_uWd0C6vxniROc5VQkrVFKb5EKox3p6bGRcVlpQJExaLixF7X_loqhRhBQPJd6E5PT8j8GUJngVDJXrLKeNrNZ7zsJRKMKINhfMTs_jhvzdriM3j00WvSJzMzIxqbfEN5Eqo99lu4cwCad8xFWwwRHHF1ZDHBwHoFA-F6On5IETKsL6RIp9AOerKFLL8hAlHQpALkBN6lkCAji0xK9nD_I1daSmBaQgjgsARtOVF3kQc",
        "places/ChIJtwclboO22YgRoEae3LsRNio/photos/AaVGc3lkh3IgROuux8SMBXt4Lf4JbV1chSrB0XbknS4aB2Y69qppPfNhDMVryITosyRuN04sMAsZngnQ_dY6iXog2WU6_3luAnSPsbAqeOd0fQHqOOBwS0CgYSJEL-xtn7Wq-km1-YDjZGu-LOxEJUYr1-bXPfN8weFhpL4I3at2LQbVloBA0J8Wz0Y0AKZlCnI_x7VE2gCpzSMwhJ2O2Q6EUH-cgLLZTaTrt5nEdnun3svVQFT7Q3KY7qFiQp96-KT7koqsDrptNDpxtKdIZMrEqblCAbmN1SD5eBl-ZEoPlzXeEpcCbyp5F5BwBi3kL6CFy7r5kExZTyoT8YyLrecE4ZhhxS5ZXInmFtKBsbigLs6lyO6G10U5XtSP15h2iNO_ZP3IUa5ry7EOyg7HmMHDbCM3E-Z3Fe4hnVLXbj6pOA_7ESol_FHy7G6ohV_kXd_S",
        "places/ChIJtwclboO22YgRoEae3LsRNio/photos/AaVGc3n2GeamMT77OtZsdrCe1nlqLx3vj7JNqvGNUfmeogNTkm5AmJeGCeNgV3wwNFLmNaDRxH_R1oc_aXfQSl4R5-TivSdP8jtf-YMZcIhCC1OnPzyuVOjdzFoQeXlmHhOlYphNGzO-tuFXAI048pD7cmEq7dTAzeb_KDAQOvpJQxoNSBGgp1buXgCbtNA-9L5-mTdNhyLoDdKc0EET_GN08pN9JKH-wc1lK8DvOcnrLNZ8ajPZy_-t8ydsISxZoEVgJ3fqZwcC62bUiW5y_K_zO1k8HKgF5Vf7HOgJmiGGwCXvpZ8gbXn4qdFlP0C-LedYe7RTmP1zL7L1esEJ7PS-zNCMn15_5t5rhb52akQ-X0RQt6a-K-Mc9NxyIwxGmW_05RkMKSjUG6-J1ewHaB43nTVr10j2r_OI1PS6ofuWvnvdZzjn53p-9XipjMnK8Q",
        "places/ChIJtwclboO22YgRoEae3LsRNio/photos/AaVGc3nInCmIYZ0SFNYbXBp8jBdQb6S7zm2mH-WhVOG0oSc4BUcuq0IONSQj1HRjJwutpOdxn6QGGcaptX2csD35ZWHFSZ5Oc3RAmM9yekBngZjQpfBZhDHgjeYyHYb9mf-JFSgFurUwLTawntlFx7bWHg0-5LvPajhEYN6R7ohI_P_2I8B5TPvV91RBdk9yRpYRWChokN6XvdIGS5lQoJau59dDvkLWeVMEXR-xuIq9Z4Kdd2N-pGqSxrMvhJ7RUkZHAwPDflxMGgFZ_SjtReYr7cfAz1NwP020ZPAgd55tpCafM82GEFgaGQnrH9pcn51XrDbU-GetfPBsvKLEsvZ34wwAC58wxPMgNZsOnIwDweLXqj1YvzinCUd3U70pVf02ZkftCwZPse0yhUtJTMXmvkQABg3r0zTi1IAEVDePnC_eP_YxDE_yUXADOz-xY9B7",
        "places/ChIJtwclboO22YgRoEae3LsRNio/photos/AaVGc3lthxNPctoOxbaYkg9o9zJA409mfHjO6r70pOp7Yig96Sp_AxUQP6yJLlULfb2C5FdVT2M2Me3JZaWYwcNjrglw_Aue69-Df21GregR0Mucq4OULXYynRLgowbSvgQQhp6Ian-7P9s-TdQomz3oxVzLgYUtMT9k5wjaeQKXRJEAVxmXHFDYzFeOFkxe1JeRLGzu9FMZbg0L41YjAjuOmCIjvMz4kPPnHIcVMfTX9n_G-Xo_xMWwMaN9rMfF3u4GaEPgpwwVesjASwdkfqL6I5Qnp9MEjIOcyp9FaMK4vDaCUYNUtoeAdrL4NpUhyjj-rdVFzp_UA1sEj-ge2VBWKBqQJx8okA1wH3plbelrSrYIzF5c7vUaSvqR_tZ4jb2m3y7cd5KR6qgdfFx9BJJF_WUXrqblrMJK8NvNNk6LwugIto3G37coBN3k11_wKqm5"
      ],
      "lastVerified": "2026-07-06T20:07:02.709Z",
      "editorialSummary": "Chic cocktail bar atop the EAST Miami hotel featuring craft drinks & a tropical rooftop deck.",
      "primaryType": "Bar",
      "priceLevel": "PRICE_LEVEL_EXPENSIVE",
      "phone": "(786) 805-4655",
      "website": "https://www.easthotels.com/en/miami/restaurants-and-bars/sugar/",
      "amenities": {
        "reservable": true,
        "outdoorSeating": true,
        "liveMusic": false,
        "goodForGroups": true,
        "servesCocktails": true,
        "servesBeer": true,
        "servesWine": true,
        "restroom": true,
        "wheelchairAccessible": true
      },
      "reviews": [
        {
          "author": "Briana Mercado",
          "authorPhoto": "https://lh3.googleusercontent.com/a/ACg8ocJ80ZmSbYK0b6zR0GV1ZXEOphkmpP7tU_9uI3Bbzzscm8Mm5w=s128-c0x00000000-cc-rp-mo",
          "rating": 5,
          "text": "from the moment I walked in the door (TONY!! Was amazing, oh my goodness, so kind and witty- he walked us to our table with so much charisma!) I had the best time and experience. From the service, to the ambiance, to the food and drinks!! Everything was spectacular!! Our server Camila was so sweet and kinda and treated to my peanut & sesame allergy with so much care. She was so attentive and made sure our food came out in great time (hot food, hot!) can’t wait to come back and experience the brilliance of this restaurant and atmosphere once again!! Thank you much, Sugar! ",
          "relativeTime": "a month ago"
        },
        {
          "author": "Lauren de Leon",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjUU85PZe1dH2FS5JiLc4UVXnyy0TJnpIeSQm-DD2XbMQxNd7uI=s128-c0x00000000-cc-rp-mo",
          "rating": 5,
          "text": "The entire evening was exceptional from start to finish. We had the pleasure of being served by Micheal, who was incredibly attentive, professional, and always seemed to anticipate exactly what our table needed without ever being intrusive. The staff as a whole delivered a truly five-star experience and made the rooftop dining atmosphere feel even more elevated and memorable.\n\nSugar exceeded expectations, and we would absolutely love to return for another unforgettable evening.",
          "relativeTime": "a month ago"
        },
        {
          "author": "Andrea Rosales",
          "authorPhoto": "https://lh3.googleusercontent.com/a/ACg8ocKaG1kU0w56S63YMAFmzD7fvXaXSryG0VNXozXEXNRtmfnuDQ=s128-c0x00000000-cc-rp-mo-ba4",
          "rating": 4,
          "text": "We had such a great time at Sugar. The food definitely surpassed our expectations and the tater tots are a MUST have. The Rise & Shine felt a little watered down but their Lychee Martini was delish. I’m giving it 4 stars out of 5 because the service was not great. When you have a minimum consumption of $100 per person & automatically include 20% tip, you expect the service to be top notch. Either way, this place is such a vibe and gives you great views of Miami.",
          "relativeTime": "4 months ago"
        }
      ]
    }
  },
  {
    "id": "ball-and-chain",
    "slug": "ball-and-chain",
    "name": "Ball & Chain",
    "type": "lounge",
    "neighborhood": "Little Havana",
    "address": "1513 SW 8th St, Miami, FL 33135, USA",
    "lat": 25.7658888,
    "lng": -80.2197755,
    "hook": "Live salsa since 1935. The soul of Calle Ocho.",
    "description": "A living piece of Miami history on Calle Ocho. Live salsa and Latin jazz every night, mojitos done right, and the famous pineapple stage in the back patio. Tourists and locals dance side by side.",
    "rating": 4.6,
    "reviewCount": 9844,
    "coverMen": null,
    "coverWomen": null,
    "priceTier": 2,
    "avgSpend": 50,
    "openTime": "12:00",
    "closeTime": "03:00",
    "happyHourUntil": "19:00",
    "musicGenres": [
      "latin",
      "jazz",
      "live"
    ],
    "vibes": [
      "Live music",
      "Historic",
      "Salsa",
      "Authentic"
    ],
    "dressCode": "Casual",
    "parking": "Street (free after 6 PM)",
    "crowdLevel": "busy",
    "bestArrivalTime": "8:00 PM",
    "peakHours": "9 PM – 1 AM",
    "popularDrinks": [
      {
        "name": "Classic Mojito",
        "price": 14,
        "emoji": "🌿"
      },
      {
        "name": "Cuba Libre",
        "price": 12,
        "emoji": "🥃"
      }
    ],
    "upcomingEvents": [],
    "emoji": "🎺",
    "imageUrl": null,
    "instagramHandle": "ballandchainmiami",
    "isTrending": false,
    "isOpenNow": true,
    "live": {
      "placeId": "ChIJe4rXvvC22YgRpjGQg1PlJmM",
      "businessStatus": "OPERATIONAL",
      "googleMapsUri": "https://maps.google.com/?cid=7144650005722182054&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
      "weekdayText": [
        "Monday: 11:00 AM – 1:00 AM",
        "Tuesday: 11:00 AM – 1:00 AM",
        "Wednesday: 11:00 AM – 1:00 AM",
        "Thursday: 11:00 AM – 1:00 AM",
        "Friday: 11:00 AM – 3:00 AM",
        "Saturday: 11:00 AM – 3:00 AM",
        "Sunday: 11:00 AM – 1:00 AM"
      ],
      "photoRefs": [
        "places/ChIJe4rXvvC22YgRpjGQg1PlJmM/photos/AaVGc3mqq-aNk17uDRZ4wdvGRD9K2ipNeDmqsDAisJsVkvDN5M5K9EBXRmjxj-1ZpZ9kE3lz4ZzT_YzP8qaVTMbNGNHIppKfcgoXdGF3cUAkC4ZlEwRRJabDG5651GHr7EZwmWyPRaYIgrNgwGy-bhvCfrqCyHZAAQS4tpZyAZhz1XP9FOMtvf8EOQCx6SZErV-buAj8ImROIx3PYgPZR9-Jd1yW_nAiT8EcQsl0QUdSrBwpz-wbI7-3GAj80Z99xkuWsSP8rSnw2uWgJKnoVqQf3SvtVJq-XdoPX7TUyf885R43ZbL2aclLR-hu8yJ5wDSOkMOV8Vu_kIkhtiytHhkY_4KoD0SS0hRWNe-ZIxOmEH4oX0m1LQyLMfzxoVQZrdO4zGppWbIe0LOd5cr2eaftC9yxwVN-LJGM-kF9dfSmzd8cHuI",
        "places/ChIJe4rXvvC22YgRpjGQg1PlJmM/photos/AaVGc3lukKQYlFyWuRKuTr7fiXAOFVY0M1gdAInN5717b4a_K39RvbEt19kPwTUwN__7UVhcE5saHPK8MHo1fnFi7qkfFhflrEOU2uZNPHPmfLS5fLb4syICV9-x6ZLA209-8B50vPIuwjyEIzfLxu5Rt3JhT9tbQLsyW8_ZKG8W001kjQsEyDg-xxMN1v4HmKhKj3E3hU9ye9f5OGCh7NIzcFgRhjixwpZmRKgNiyI67a-DJIEWFeEjnaVDrYpPrEsv_t0kZKG8OuzfyekQDdJ7sAiddToDPiGiuXBQeYamyk9rDb2bnql5UMH7wi05Jz8F0FXoxSBdN3am6qbLbtY7CMLpwmdy3HCUgaPfKJRNJK1aVT1BHRGialY9Ep1MkxH8FhI4tc3WixW-iDin3IEeM3DTYoNGTE_rFiJnSV_SR656c_KR6u01fLrvnGvfBrzU",
        "places/ChIJe4rXvvC22YgRpjGQg1PlJmM/photos/AaVGc3m1X5FdrDfuh0u7AhdqJG-GUoUqnU1g_zpjqGlVvjCBKj2G4Ld4xDaqwTErTlYlezXrATOJ5ELsiWO8n9hQVVX64KQNghQgNj30oAg_jaUUsh1_DsL97YIUZpy8NLQPuM5Xdsbc80ixwjWgX-rsxWLfA2wA-qF9zK5W-OFLDdp58sttV9heAV9XZ2-g8AKWLJ7LBHJ4R9Oq3UQSezgtAvp8CVk8hHxK1wfSx8Igd403JJKToPqZg9PK7OMCkEkcw5O6urHbLhrtuDyyxS9SBYAQiyqHYz0hVYimGO6enH-30VurREASbAir2xunKjRD_AAXx_gyq2Fh_yX6EZW6lnJmYyZnyaFkUjgZVNapwUYzudcr8DCuVEPTS6wTXEh2ewHym3vya1QYyZC1Mj4_nr3MYx9AhRQq6K78JfosZ570kA",
        "places/ChIJe4rXvvC22YgRpjGQg1PlJmM/photos/AaVGc3l_nEjerAPTm9bvLbiT64BkGXi_yDYREh-afYKaqN2rIEP3L_zMU3Zo4laVfoFTvCxA27y-bVO_QMXLS4bNSIrNrRDMINszabSBPxt9NzzKWwQNbqbNfcV5Ysfcyra1bYqlh6zf6DpzvLxsh2Tcisez0lCBwF5iNcM4LDIcSCYnIzmHdAva7L6LXBthFXHEtCmeh-TCO6Puv72Ie14kZMK63NRqt_ydIB7mV3vJo-sADRyF5YzKlANJvi6FLLc_71kgLdbe4QggpUQaq3Hl-o5vI5YZkEua0YuTtLL4rYnbgwHAcWUQdsP_ILQMc35lJHY1Q6u-8llOy1V5D7jjnmpyFbVObPVv7cD3XQ7jrADXSUh8Dj2F57AbUCghXDZ-XbSHOr2iUFNmRdXNelnjMGavzbNcHiuimcCRGMhXZCfJkKmZhIEbo9stxy5_MbEy",
        "places/ChIJe4rXvvC22YgRpjGQg1PlJmM/photos/AaVGc3kgw09Jqzim_Ow7wof-xwuAdqPUZrL6zHA3yy7lz5g1J4M5kHagsdWu9JiBK6gHhoS3A2bfrAfZPJ2bkOGK577g2LrgZj2yWpUF1zQoL4sKFtlPpH8x9SFyJVRAZvXQGX5--c2Oeh3opfRnF58Jn_WIIWuQckd-S1h_Eu0mVczbHXcvjv6UedsxY0TSXpdXub0LU-AUiti85MuvwnkSMyasGjfFf-75CDGYim8h89rIfLgaK2-hV1ggw-z1kmacVK2YrDRjsE1VeKZFI3GQj_x_O9VSrhmh0U0y-XqFFdEG74ZwAYcwIdtyNExiiLq8A3HVE1wf0mk36Eiw26mdgmkxmIQ7Wcw1fwSq-oAQLYWIgVs0fYNp1VdBJdJ82ikNfJi-fw1oEKGHsHbUgICbOgc6VVLHqESXy_0OZ28Yv-QgoYBTmrZk1zP3RmA4blF8",
        "places/ChIJe4rXvvC22YgRpjGQg1PlJmM/photos/AaVGc3mRJpcISffcmKZVjlUztIq-y18u9N4fV6FX1r5jYce68a__PHxuWwZaTKJ8viNcEg3mZwOx_30Swygcmdv2l-gRR-W_5sFCsuJWi8sGejYceLvichi7pRcxRuzxwWwqKc0SqWVNeEDS1SZk26-I8oIATX7M6EOcWcHf3GS7Ps2klAjf0pSlwIryWbJ2oHFm5YY7NHA-mZXy-pOfvZJc3Npqrn2x-BAH9aWkOy76mLB87gOPDWfZYxKxNBanaqt2swDK3-3TUibcGCprHCK6q7GQ4lUEyDKMWvP-z_7M8DhA3-spkLPEg08YNqoPkMMdvVIeU08tObjFkzSftdjRSDI9GCzs8r1lch5gZIUfvlaAg1Prk917m1XG51pTF48J7h_9TImFXW5741mSSYmpuGA_8tVjp8i_WXlkqzGoIZQ_3qp_GCh-cxSl3FCGYA",
        "places/ChIJe4rXvvC22YgRpjGQg1PlJmM/photos/AaVGc3kCvVpRi1Z6Bsb56N3CKkoc3sSgAASG6vKLsa-b1jEIBeuXEfcGnzlCmykKRNSFSTCCPR6LWw01HmlzMsIhL2KPXp7fk_cVijPutEys1sDL5den1kL9xocL_6k4T_ya3sI_YeFKEMRf9zeMIrw8-g0Twi7f_VfGKozkAlozDPOTlU3yrQo0G58W2hznF6y-U71Ix13KZQtac9KcZKBZcBKALHEUa-6LXU0gwEBY5EHC98tNXE6o50hzJA6vT0cfDaqvLJgxkFkjCxMgjspGb2x7JVvnwXPCp82BKCaOa-Mq7Oar4EbpvULv0vKoGc9MDRrsIt0QtM6QytBZSK60KSTv5v08NrT031dqmUXcwII5s4pXEt5zW3-m9q5JqYXYHI-a1c925yHj-1ayLJ5cycpMhgRgG4fxPmfg_jXTuxoabQgJLqSZerOVk4ZyTA",
        "places/ChIJe4rXvvC22YgRpjGQg1PlJmM/photos/AaVGc3lwmNqbpEBLMXRz12yrHSfWUG9sqMAyWy_GgWG-P_Vr00ITKWkXbGhpeLSx4PpelYFzp16Xwps_Njq2ON97XP9JOyAxnFf8AgTnZErNo2WVDDEolqm6ajfnfVQScgsJQmvPJWAYaFzg2aCbQtKKaOMlckGCPmHDMt2_Ettf7UKUDPPt6aX3Bbb-mQseg8ugvt1aZx0GkKHi7QqeMrOVwp8sT_tjZHwxkkEGLTYR0yIv80WY6bWytAlkiOKqSfdVVX2jLiCQrj_bHTSPQS3AmYqJ0Y7MOgwBXKLOAHmGICOkTTaZpIEL4nZ4iU8IZ_xcOlCMKQhskgvyTyHugmhGeAnjIfnGu8jm6A47C_ON4uMQJjVEVbSW813h64K_azQ-3aKSduw7AAJSKLDmo65GHojJZ2_1n7oW_pu-iKWFmVv3RuU9H_URYRnTZ6n-t1BA",
        "places/ChIJe4rXvvC22YgRpjGQg1PlJmM/photos/AaVGc3lq5WgBQl10_Noq6fiPcZmvuCSErJqHBfqRyxCFm0l0Ci_6dRWAP1MLXIOEGmt-rkPyLyM9PRtHiV6TB6dXXP3j_anqBv614-p2GPCiE0ztTcsW6_r_l3VizmGNES5Cehf2IBQqoAH5j0JcxzLGzcn4JD3v1liEbGXJist6SArzPZdmFxIhz8OxcDKtVAz58Nh8sbTQNWmjBx6FJbSHTeplq-lrXApIKjuiPJ_6tuYLl8XRlDuEnCUAPv29NbwXF8qvGfAQYTxueQ0J2sQaxeXMjAiNC7nLHt9S_89eB774QhRxJJYuSIiAaG3nQSm6tp2qNm5NAv91fqvcVWAhp1Y66A8Vm3N0EBkS2K-3U4odGlXriGKEd589BfyPQFzZ799y1U2t2ZqiwP_netJHGkB6edpyoBux2Di5YM3InRZvwTUQzgXbchFGlTO3LK2G",
        "places/ChIJe4rXvvC22YgRpjGQg1PlJmM/photos/AaVGc3lWu9wojk6YsTLM-aGjRF8JBRwmaLem1D8GuAAQdCKEeBMtG4OCW4d7Sft1V8K0eJ-lYEbMOQ4IvQPe8K2Of8qqMWtHuixmzP1DGMkyaNkwGIIy5snhyNVq6nUDT2Pl3I_jDZpFEEDrOzbnFM1LTVmwyUDnkyp9RPZoDJxzAU9g1w1FcArbAVlY-V9qZQNhifwGs_042twoM9u1cZibIhEWeowq5gVUGo7NTg9oXKlhlzNAKG0pib6ZBlBes_FtVdh2Y5aNyhxJone8bQGgEGOLMgeC_fmOLoM8o6ZbaGxJagUJLE6Uy7BPItrtQCCeBVKSJi8IqIlOLBzhW67aDzIjasE31YzAkNgeGvGT9Ky8aqXKb7Aoj1VJ9NavOIxW3tT2sdCrIhsq5aMhoSkDyBg2BsIK6nqf7ctGzGJoOxNYUFdP13mIQAu1cMoTXTec"
      ],
      "lastVerified": "2026-07-06T20:07:03.207Z",
      "editorialSummary": "Iconic nightclub from the 1930s-1950s reemerges as a live-music venue with Cuban-style food & drink.",
      "primaryType": "Bar",
      "priceLevel": "PRICE_LEVEL_MODERATE",
      "phone": "(305) 643-7820",
      "website": "https://ballandchainmiami.com/",
      "amenities": {
        "reservable": true,
        "outdoorSeating": true,
        "liveMusic": true,
        "goodForGroups": true,
        "servesCocktails": true,
        "servesBeer": true,
        "servesWine": true,
        "restroom": true,
        "wheelchairAccessible": true
      },
      "reviews": [
        {
          "author": "Mafe",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjVanie-mSQANEJWEWjr9MS2uQZIlXVPgnWR36CbSMJ_IeqCqBx7yQ=s128-c0x00000000-cc-rp-mo-ba6",
          "rating": 5,
          "text": "My friend and I had heard about the free salsa lesson at Ball & Chain on Wednesdays and decided to finally check it out, and I’m so glad we did. The salsa class ran from 9 to 10 and was such a great experience. The instructor was upbeat, engaging, and had great dance moves, calling out the steps as the dance floor gradually started filling up. After the lesson, people stayed for the live band, which was amazing, playing a mix of popular songs and keeping the energy going all night. There were dancers of all levels, and everyone was incredibly welcoming and friendly, people danced with everybody, which made the whole atmosphere feel fun and inclusive. It was honestly a joy to be there and meet so many interesting characters. The staff were wonderful too, from the bouncer outside to the bartender, everyone was kind and welcoming. We even found out Karol G’s conga player was performing with the band that night, which made the experience even cooler. Between the class and all the dancing afterward, it definitely turned into a workout, but the best kind.",
          "relativeTime": "a month ago"
        },
        {
          "author": "Maling Sun",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjXLxrVpvBLeDjDbqxSw5ebEuGE6ULYMthOqllAX6mlVH_M9G0Z2Ig=s128-c0x00000000-cc-rp-mo-ba6",
          "rating": 5,
          "text": "A Must-Visit for the Ultimate Little Havana Experience! 💃\n\nNights like this make Miami unforgettable! Stepping into Ball & Chain felt like stepping back in time—rich history, incredible live music, and the best energy on Calle Ocho. It was easily our favourite dinner experience in the city.\n\nThe service was outstanding; the staff was amazing, constantly ensuring our drinks were topped off and checking in to make sure every dish was perfect.\n\nThe Lineup:\n* World Famous Mojito: Refreshing and perfectly balanced. (during Happy Hour, buy one get one free!)\n* Vaca Frita: Crispy, flavourful, and authentic.\n* Tropical Ensalada: A perfect fresh pairing for the meal.\n* Virgin Piña Colada: Creamy, tropical, and delicious!\n\nBetween the live band and the 100% good vibes, this place is a total showstopper. Don't leave Miami without stopping here! 🍹✨.",
          "relativeTime": "6 months ago"
        },
        {
          "author": "Gagan Kapoor",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjVfqC9qGwwJEK22z4eUGaSge-vUt7UORZBFWE_rHweBm1iczZ9szw=s128-c0x00000000-cc-rp-mo-ba4",
          "rating": 5,
          "text": "Being at this place, listening to music, sipping a mojito, and getting to understand that you are sitting in a 90-year-old pub was absolutely amazing. The ambience was absolutely eclectic, with live music all the while I was sitting there. Everyone was enjoying the salsa, and usually everyone gets up and starts dancing to the beats. The atmosphere is that infectious. I spent about five hours at the place and did not feel bored for even a second. Absolutely loved it.\n\nI tried their Jerk Roasted Chicken Wings, and they were fabulous. Also tried their Margaritas and Mojito, and they were good.",
          "relativeTime": "a month ago"
        }
      ]
    }
  },
  {
    "id": "komodo",
    "slug": "komodo-miami",
    "name": "Komodo",
    "type": "restaurant",
    "neighborhood": "Brickell",
    "address": "801 Brickell Ave, Miami, FL 33131, USA",
    "lat": 25.765616,
    "lng": -80.19006159999999,
    "hook": "Dinner theater for Miami's beautiful people.",
    "description": "Southeast Asian fine dining that doubles as a scene — three stories, hanging birdcage booths, and a lounge that turns into a party after 11. The pre-club dinner spot in Brickell.",
    "rating": 4.5,
    "reviewCount": 8986,
    "coverMen": null,
    "coverWomen": null,
    "priceTier": 4,
    "avgSpend": 130,
    "openTime": "18:00",
    "closeTime": "02:00",
    "happyHourUntil": null,
    "musicGenres": [
      "rnb",
      "hip_hop",
      "house"
    ],
    "vibes": [
      "Upscale dining",
      "Scene",
      "Pre-club",
      "Luxury"
    ],
    "dressCode": "Chic — collared shirts recommended",
    "parking": "Valet ($25)",
    "crowdLevel": "busy",
    "bestArrivalTime": "9:00 PM",
    "peakHours": "10 PM – 1 AM",
    "popularDrinks": [
      {
        "name": "Dragon Fruit Martini",
        "price": 21,
        "emoji": "🐉"
      },
      {
        "name": "Japanese Whisky",
        "price": 26,
        "emoji": "🥃"
      }
    ],
    "upcomingEvents": [],
    "emoji": "🐉",
    "imageUrl": null,
    "instagramHandle": "komodomiami",
    "isTrending": true,
    "isOpenNow": false,
    "live": {
      "placeId": "ChIJd6C8AYO22YgRYuO-L2IUdDQ",
      "businessStatus": "OPERATIONAL",
      "googleMapsUri": "https://maps.google.com/?cid=3779668399211078498&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
      "weekdayText": [
        "Monday: 6:00 – 10:00 PM",
        "Tuesday: 6:00 – 10:00 PM",
        "Wednesday: 6:00 – 10:00 PM",
        "Thursday: 6:00 – 11:00 PM",
        "Friday: 6:00 PM – 12:00 AM",
        "Saturday: 6:00 PM – 12:00 AM",
        "Sunday: 6:00 – 10:00 PM"
      ],
      "photoRefs": [
        "places/ChIJd6C8AYO22YgRYuO-L2IUdDQ/photos/AaVGc3mOQbdtU2ADftbsM9V1L9DRT3vYCD-FH2yDhQ9ySwfK7JNSf1mf3Fq4QheRNBIUGMWU_6NSUpNmYU6tpJzcKh6T47-sSbAg1fPYAVXPEl_Wcs4vn2tJAPXM8dxC3cvC4-LsyW1zXUbkUZoM2135-zi22-ighGGD6VVBg5q9sMKLjLY5y1YRKan8rsPIuBGNNO0T4DShO-C87MZGKAxk-rFeqZ1y_UmICvgcz4diLBcIt-BTJOPIGiKZE27RFFfebmZinwuLFrIceIUzLLesIHcz79hMkQ30ZbUJaVMla_HW39XheyLnn5pW-ZkYufVfc2YZN9O1KI1G60dG0yRyfBVfllKCYQfZqROecoCgjQkqjDb6uYW6HknzmhW9diQLzxk_Yd998AQDrBRzah8XLuIjLE1L-V__1tO716dcj8mYBA",
        "places/ChIJd6C8AYO22YgRYuO-L2IUdDQ/photos/AaVGc3mee1cXaZvLXfkGCZzKdeM_zaM8xFneQvNPogiOtzLMrQ_--dkpbDpRjZkzeyw4C38XoUY57dDG7g9IAXDGkZWqdiMET8oa31SDwC_Y_pMyiqIMOkDNfv3ephlofmQmAJg2T8c7TdsQLo_aZbWwfyagBR0W6f6sQY41JZ7LFAM4GIbYvN2opwA7VHMh_krT7b8Ev_llPavPXoeA6LwmkstXklumDtj4I31kDBXy7CRIHRdxqJ2v7nmOxiRorH2cuZQrSIfdbci5jB2uCUQbjKDfpcv59Y7tyon8d6JWb74P-xZR_uq1YBuIKnfhgOVpx0jIF993zghsn-aj9tInwreagE3u2ugZNIWmjM4A_tx_umRUwQCeqdirO8J8sG3zCukikqwnVsJ58HRk1iyhduEdmEZTKpvlOiK5YMavIc9gxElyit8H8ds23JTKwi5e",
        "places/ChIJd6C8AYO22YgRYuO-L2IUdDQ/photos/AaVGc3n8jE578TI1n2OYjd7EOus8Z5cvGU7YG8Dhk0H-sA5oio6HclkwPKrajhV9S2k2tVxtxtTMFtHzVclrHODZEwIeDjVe2WyCjaREV217M00ObTixOBImGffpKwHIVrTQ5cmSkM1CHnHvQXjrg_WwQYixU74pgg163VwcNYEcvbk5cghIyJIRV4yM5D445zkW22HL6GHLT-_fsbpN_xBepYjIovO-RGsSFX3pR5YRfO_G2f3mHRgS7UB7wuB9FOM88COpngvoPezdRoj3dIG2EPUQM9TuG1Yqoh1OxlN0C2ZzIEsQflSSTVOBNjFwFWNY_38KsuWF_liRH1DUzYujaryF55MgCyR_W0jKt8CXgVgWFpnVihkTMuNyqJl2pNtEWYYmciOF39nyVOpmGrxmRVGE1z4A5GdLNK6H59x1NF-nK_C_cmSuG1CIwW3a3AXW",
        "places/ChIJd6C8AYO22YgRYuO-L2IUdDQ/photos/AaVGc3nGHy7xn3OZvEVGxnKBKCYJ2VMYPRi0NhwbP7ttrdcuRIMfLTT8v9VaNPH6N7D7o-_aJl7VG_EMdqEtltpn4Y3rtNqdipm2a_iJ_yl7RfLC2MvHH42cNFyZIog_wkRfm8TizeXmCOTdpaNRJU6FdcrTmvcKG0ngKqiHbRYO9P9ssFxw0dNzQjLlCRtoh5mHfRzXLx2qogkkdpRqFVUIjMaKF-A5qylvJJQ1Bfb5ggV3XpCXmeTomYNpSpukVw5f3RAz_k5nZL1uZwCFdu_hVCltZ5plu20iPkUMDI8rm9FtLKrb8HW1vQG_vZAA8F_vHYHvfck5GkQwgUVXQrwAsbwjQVWXlTAuPgdJjdh-IKMgcrXluOovzsztMhP9BxgjU_ToaT4Omlt07XSjC7JJWqz9TZv4ytFEcNQvPbnqBBEB9Da6X_qMPYsw0z3onQ",
        "places/ChIJd6C8AYO22YgRYuO-L2IUdDQ/photos/AaVGc3mC2oPPEuLgS1um3ggleGTzrNIw-nPyau3shjvUXikE9Br6G2Fhvth3J1w5Qd-HvOuPSVJjFz7wkOFlomra5zy4NZ6baPRO37ACQU5pFRKWZhtE2vvA1i5b3Bwwmj_ZIRKQ9Lc0PdAiqIYFtU7M4vkaj-3sKT6LF9Z3HnGrT71HPVqaDd2SO3tP5ZwIWQEyy1Vp-_FcJYdMHLzrK55hq2NB5PwWqhb7ohF2ONSbIJT0aOs9AvOeGdmT8gbjo0UR4C5VORTeZs7zvfGY1c4yMKemMcoSfWapD8ygtKnuyhHeUi7s-fU-CGrdRrZOum6G2dz_FrOqKAUaQwLSdBOzxk9aJaDsiU9bNrNpUrm5_z8kgkdJ8rbHcl71iOJvPp_OiF5R-3AE5TTPvFmjct5kCKrP85gO5Nj1yUn0LRT0MTvZFe-kMCKmst9ZPbyz-w",
        "places/ChIJd6C8AYO22YgRYuO-L2IUdDQ/photos/AaVGc3l7bAptQvbHB2WsN-abhtdr2Znsb7P83jKsKd8IcOKHFv7DwgPKxrBSGkRGf-FQ0gNPEfSxupvwo_MySnvqBPWtiw04aivHHC6z4qq94orGBNOoIPFPdvI2Ia02nQ_RzQyLJG9hG17pHvLJMPqBtkK7YTnXuh5ZdS4rRwN5rS2eaVcxHsDSMRGSPmFQpabjPsBYBUhEVCHhzro1LTzJEYTk71knOqVygZ6bzZTbXK33UGAK4xj3o_iorFdBLS09m8KB0ppyi7-hvphdP7h4qUaIsNaXoKDC_0Kt80eprCsG32gSrgtNZLY9BfkWpMHwEAOgN7MidQSfS3Ii72-8sjm_c6vR3YfHzGO-QdqFAQK2FjYzKVq1SyHDCG2Xq4HfqXIFSvnKHwP8eH6q8aafYfY8AV0xdd6EaRLggCJPMGWSSuZgzKYbV50AB1visR6W",
        "places/ChIJd6C8AYO22YgRYuO-L2IUdDQ/photos/AaVGc3n8-w4_FsIHdJ01TscKwGCa0d1_8XHLsEQaTAlW__93TVUzrLZWSuPbJbNzZGw3w-zmzH9RcPLRF2OOk1JWLBWaJT1j4N4LqRpv3ItGOw0tuuXBVuVUlfMdeRJpICrt3gq4I7ILt5G7oaKHQLJ4GDdaBJ0vzBfdS1jHcu85FZyg0aVlxjawPkJykI1hPVcIeEz5OCdGfSW8Ke-SWqOYPZnLwpV7I97kqAIjIn5eFzJTgWmcel9qph5TsS4ucuR_tbPFW-2rfhv_z1L5py515UoH9F49dojBnSUeKzaMtaBoKFQJmhpsLBj1Vs4z1VK2cas_EzzChI1_k3gjqUIm1W1NkVwbDXgxOpQvSz4enkCu4zo88KVkr0LeEjVqvW4kYIPC28Cj9i_3_Qw_RfraCkoZz2MKbsGSbeJ_AYY9M9CkY2b1wqkz9KT9nHiZHA",
        "places/ChIJd6C8AYO22YgRYuO-L2IUdDQ/photos/AaVGc3n3RQZg90Hqja-QKv2tT2yDw8rps9zb0uvvVZj77CEAqBb9RCNEclH3SwP4AT0a6z2hL1-yBqIzp1sVwctVhxhITXlHtnjlcMAVGgMXQG1Zo_fGB4i_RI571ZIqClYD8QBHYHBo2cNnDYiGDytHWSbuVK_oEIrTpLywOMWVxzLNAODyoh9Kme3Ni11XXeNJUKnDWc8ARqjxFg16QbcQyWt3mlJE0VZ8rnDve74LxnYPkOZQIiyPLqmUsg9M2YQKWNHPUf9zgRWK5t5xXDd1KWbVrfVbyNFg-0AQE3c9Ihqr0bdSik4GgmGuOBIuOBa_lAlqRqB_IrRcfMlpHdZeFkQioMPEythxwlfgWReHvijONgNxqph1joucdtZ8IzYCnjFianJ-wcI2_vU2uCHjssJyYa1gkj8pZ7cJozLrDsJszXwqOcTSDjcfcM5XL60T",
        "places/ChIJd6C8AYO22YgRYuO-L2IUdDQ/photos/AaVGc3nPyoOuxHzowa1CAQV7dv5N_vKmg1536PxuuNvyIOAlet_0GGt9EMfWMNtL447NhA11Z-k5SfXklzm5s5E4kfS-WSAxHCO4A8tlXT6FRa9P-X6YKb3u0U3ayqA0JvCX8vtrLY0n3-VZL113fSfr_lBOxHdTvyJW2skA8i_FxMgG41iqdnWb9t5ZgX-56oZLaSIVABdApuis97p1dqI66M2zh6WHhrfWQOgE-keKFrQJd7BL_D0PCXayTUUoRXX9bLDj7dhd3uCW6SJVWjfKbL6juNULbAiKFLt-GyXy83jiq1sdnkuUIBaKjyAzM0D1TGoN49eJ2FqL5jsNtD0V4c-sUTDRH4JXDZMt22ujAMb4ErTeFmdalS72g2dmrlLxQL2UHQ6hOeTzixL3IOEpSQfmkDk4QWzobhLxAHCap4YylA50xKFH1o6Hp4-3HUiO",
        "places/ChIJd6C8AYO22YgRYuO-L2IUdDQ/photos/AaVGc3k5Mp-d6DmiA5oT-owj6AFLhyTHqUdmppB628bxZ3uRCV4wOcsm9A-7rGnrswxCNJ0PlHGA_haymEZTAI3wJRNFhXCcC5jKiHCmJofbFGRIBr2M9qU3AxzHQE9x88NB5zDvOLzvxDD0QpbiOZHPqSZctoOTCdp7aXIyUxJiw4soLOzzYYWBv1Pp4RstZxO0KIPnKG4Rad6ALD13QvOfSbZ-apI_v8gnmZMc2zH8NGwXEMik0h1HA5G9V4exAk6r-u2v1oO5DUZ83MuouwM_7fpesYnK3fcohBDl3f2kna8phPOIcpAyx9dVA0WphunFJquCJ6c-kDmUmog7JATAyLTinQs9MNF5INTIjrsHhhSSTP7R5-AHS4ZmcbB9QN7EEYVy3MAYMfliBFZgFe6ggy6JGQL5sPnEQkFRJPXhOcKo4DrcErpaKZHQ1pyeFAu7"
      ],
      "lastVerified": "2026-07-06T20:07:03.704Z",
      "editorialSummary": "High-end restaurant and lounge serving Southeast Asian plates and innovative cocktails",
      "primaryType": "Restaurant",
      "priceLevel": "PRICE_LEVEL_VERY_EXPENSIVE",
      "phone": "(305) 534-2211",
      "website": "https://komodomiami.com/",
      "amenities": {
        "reservable": true,
        "outdoorSeating": true,
        "liveMusic": false,
        "goodForGroups": true,
        "servesCocktails": true,
        "servesBeer": true,
        "servesWine": true,
        "restroom": true,
        "wheelchairAccessible": true
      },
      "reviews": [
        {
          "author": "Carmen Konert",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjUgPsKbzJ7YiEhwzt4SdiEZw6Nlzpk-eCpsP9i0terrgZ2PyLCq=s128-c0x00000000-cc-rp-mo-ba4",
          "rating": 5,
          "text": "Douglas was absolutely exceptional. He went above and beyond in every way possible. Not only did he provide outstanding service, but he took the time to explain things, share recommendations about the city, and create an experience that made my guests feel like they were the only people in the restaurant.\n\nIn an industry where great service can be hard to find, Douglas stands out as a true professional. His attention to detail, genuine hospitality, and ability to make every guest feel valued are rare qualities.\n\nI don’t know what his role is beyond serving guests, but he should be training others. In fact, they better be paying him well because someone else will recruit him in a heartbeat. Employees like Douglas are the reason people return and recommend a restaurant to others.\n\nThank you, Douglas, for making our experience so memorable.",
          "relativeTime": "3 weeks ago"
        },
        {
          "author": "PLAYHOUSE DESIGN STUDIOS",
          "authorPhoto": "https://lh3.googleusercontent.com/a-/ALV-UjXLd6VPFlU0F17CNKa5phJ5xXEZoMTdJ4AzVSzhIMNN4D9hxa_z=s128-c0x00000000-cc-rp-mo-ba2",
          "rating": 5,
          "text": "My dining experience at Komodo was exceptional from start to finish. The food, cocktails, and service were all outstanding.\n\nA special shoutout to Douglas, our server, who was attentive, knowledgeable, and made sure our experience was seamless throughout the evening.\n\nThe Hamachi Crudo was incredibly fresh and flavorful, and the salmon tacos were easily one of the highlights of the meal. The chicken fried rice was perfectly prepared and packed with flavor—comfort food elevated to another level. To top it all off, the lychee martinis were absolutely delicious and dangerously easy to keep ordering!\n\nThe atmosphere was vibrant, upscale, and perfect for a night out in Miami. Between the amazing food, great cocktails, and Douglas’s exceptional service, this was a five-star experience. I can’t wait to come back. Highly recommend!",
          "relativeTime": "a month ago"
        },
        {
          "author": "Johnathan Sapone",
          "authorPhoto": "https://lh3.googleusercontent.com/a/ACg8ocKjUUKBbWFQlHve85SSk_3gMUyXjGPJ56fxiKRcGlvIi4pwRg=s128-c0x00000000-cc-rp-mo-ba4",
          "rating": 5,
          "text": "What a beautiful and airy restaurant!\n\nThe venue itself is fantastic at all times of day.\n\nThe service is on the ball, very nice and quick with attention to every detail!\n\nLet’s talk about the food now, they have a large and vast selection of well-executed Asian fusion dishes.\n\nOf course the Peking duck is a must, probably the best I’ve had!\n\nMy only remark is that they use the same spicy sauce for many dishes and sides so I was kind of done with it at the end of the meal, even though it is great tasting.",
          "relativeTime": "a month ago"
        }
      ]
    }
  },
];
