import SwiftUI

/// Runtime language switching (ES / EN / PT) — no app restart needed.
/// Views observe `L10n.shared` and re-render on change; the choice persists
/// in UserDefaults. Adding a language = one dictionary. Keys missing in a
/// language fall back to Spanish (the authoring language).
enum AppLanguage: String, CaseIterable, Identifiable {
    case es, en, pt
    var id: String { rawValue }

    var flag: String {
        switch self {
        case .es: return "🇪🇸"
        case .en: return "🇺🇸"
        case .pt: return "🇧🇷"
        }
    }

    var label: String {
        switch self {
        case .es: return "Español"
        case .en: return "English"
        case .pt: return "Português"
        }
    }
}

@MainActor
final class L10n: ObservableObject {
    static let shared = L10n()
    private static let key = "bp_language"

    @Published var language: AppLanguage {
        didSet { UserDefaults.standard.set(language.rawValue, forKey: Self.key) }
    }

    private init() {
        let saved = UserDefaults.standard.string(forKey: Self.key)
        language = saved.flatMap(AppLanguage.init) ?? .es
    }

    /// Translate a key. Falls back to Spanish, then to the key itself.
    func t(_ key: String) -> String {
        Self.tables[language]?[key] ?? Self.tables[.es]?[key] ?? key
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .es: [
            "tab.tonight": "Tonight", "tab.explore": "Explorar", "tab.trips": "Trips",
            "tab.plan": "Plan", "tab.me": "Yo",
            "greet.morning": "Buenos días", "greet.afternoon": "Buenas tardes", "greet.night": "Buenas noches",
            "home.where": "¿A dónde esta noche?",
            "profile.language": "Idioma",
            "profile.points": "BarPass Points", "profile.nextLevel": "Próximo nivel",
            "profile.howToEarn": "Cómo ganar puntos",
            "profile.checkins": "Check-ins", "profile.reviews": "Reviews", "profile.invited": "Invitados",
            "explore.search": "Buscar venues…",
            "trips.title": "Trips", "trips.subtitle": "Planeá tu noche con tu gente",
            "trips.new": "Nuevo", "trips.mine": "Mis trips",
            "night.question": "¿Qué noche buscás?",
            "night.hint": "Elegí un vibe o describilo. Yo armo la noche.",
            "night.build": "Armá mi noche", "night.rebuild": "Armá otra noche",
            "night.yours": "Tu noche", "night.save": "Guardar como Trip",

            "home.mood.empty": "Nada abierto con ese mood ahora.",
            "home.mood.count": "%@ · %d lugares",
            "home.mood.more": "Más para este mood",
            "home.favorites": "❤️ Tus favoritos",
            "home.forYou": "🎵 Esta noche, para vos",
            "home.eventsTonight": "🎟️ Esta noche",
            "home.trending": "🔥 Trending ahora",
            "home.happyHour": "🍹 Happy Hour activo",
            "home.openNow": "⚡ Abiertos ahora",

            "profile.wallet.balance": "Balance: $%.2f — tocá para cargar",
            "profile.passes.title": "Mis pases y órdenes",
            "profile.passes.subtitle": "Historial de compras y pases",
            "profile.games.title": "Juegos y misiones",
            "profile.games.subtitle": "Trivia diaria y misiones con XP extra",
            "profile.earn.checkin": "Check-in en venue (×%d)",
            "profile.earn.review": "Review con foto (×%d)",
            "profile.earn.trip": "Crear o completar trip (×%d)",
            "profile.earn.share": "Compartir venue (×%d)",
            "profile.theme": "Tema",
            "profile.appearance": "Apariencia",
            "profile.autoplay.title": "Música automática",
            "profile.autoplay.subtitle": "Reproduce tu música de Apple Music al abrir la app",
            "profile.account": "Cuenta",
            "profile.account.activeSession": "Sesión activa",
            "profile.account.signOut": "Cerrar sesión",
            "profile.account.guest": "Estás en modo invitado",
            "profile.account.signIn": "Iniciar sesión",
            "profile.level.max": "Nivel máximo alcanzado 🏆",
            "profile.level.progress": "%d BPX para llegar a %@",

            // MARK: - Bulk view-text migration (Explore, Trips, Table, Auth, Posts, Hype, AgeGate, TripSocial, Root, ReservationConfirm, PriorityEntry, Plan, Cart)
            "explore.title": "Explorar",
            "explore.toggleMap": "Ver mapa", "explore.toggleList": "Ver lista",
            "explore.toggleView.hint": "Cambiar entre vista de mapa y lista",
            "explore.search.label": "Buscar venues", "explore.search.hint": "Buscar venues por nombre o ubicación",
            "explore.clearSearch": "Limpiar búsqueda", "explore.clearSearch.hint": "Borrar el texto de búsqueda",
            "explore.centerMap": "Centrar mapa", "explore.centerMap.hint": "Volver al centro del mapa",
            "explore.layer.all": "Todos", "explore.layer.trending": "Trending", "explore.layer.happyHour": "Happy Hour",
            "explore.layer.noCover": "Sin cover", "explore.layer.rooftops": "Rooftops", "explore.layer.liveMusic": "Música en vivo",
            "explore.cluster.label": "%d venues", "explore.cluster.hint": "Hacer zoom para ver venues individuales",
            "explore.marker.hint": "Venue en el mapa. %@. Puntuación: %@",
            "explore.openBadge": "Abierto", "explore.trendingBadge": "🔥 Trending",
            "explore.viewDetail.hint": "Ver detalle de %@", "explore.filterBy.hint": "Filtrar venues por %@",
            "explore.empty.noFilters": "No hay venues con esos filtros",
            "explore.empty.noResults": "Sin resultados para \"%@\"",
            "explore.empty.hint": "Probá con otro nombre, barrio o quitá los filtros.",
            "explore.listRow.hint": "%@. %@. Puntuación: %@",
            "trips.createNew": "Crear trip nuevo", "trips.createNew.hint": "Iniciar la creación de un nuevo trip",
            "trips.delete": "Eliminar", "trips.delete.hint": "Eliminar este trip permanentemente",
            "trips.empty.cta": "Crear mi primer trip", "trips.empty.cta.hint": "Abrir el asistente para armar un trip nuevo",
            "trips.empty.subtitle": "Armá una noche con tu gente y guardala como trip.",
            "trips.empty.title": "Todavía no tenés trips",
            "trips.error.title": "Algo salió mal",
            "trips.openDetail.hint": "Abrir el detalle de este trip",
            "trips.planCount.plural": "%d planes", "trips.planCount.singular": "%d plan",
            "trips.retry": "Reintentar", "trips.retry.hint": "Volver a intentar cargar los trips",
            "trips.status.active": "Activo", "trips.status.completed": "Completado", "trips.status.planning": "Planeando",
            "trips.stopsCount": "%d paradas",
            "trips.yourTrips": "Tus Trips", "trips.yourTrips.hint": "Lista de tus trips guardados",
            "tripCreate.back": "Atrás", "tripCreate.back.hint": "Volver al paso anterior",
            "tripCreate.cancel": "Cancelar", "tripCreate.cancel.hint": "Cancelar la creación del trip",
            "tripCreate.city": "Ciudad", "tripCreate.city.hint": "Ingresá la ciudad destino", "tripCreate.city.placeholder": "Ej. Miami",
            "tripCreate.createButton": "Crear trip", "tripCreate.createButton.hint": "Confirmar y crear el trip",
            "tripCreate.endDate": "Fecha de fin", "tripCreate.endDate.hint": "Elegí la fecha de fin del trip",
            "tripCreate.from": "Desde",
            "tripCreate.next": "Siguiente", "tripCreate.next.hint": "Continuar al siguiente paso",
            "tripCreate.startDate": "Fecha de inicio", "tripCreate.startDate.hint": "Elegí la fecha de inicio del trip",
            "tripCreate.step1.hint": "Ingresá el título de tu trip", "tripCreate.step1.label": "Título del trip",
            "tripCreate.step1.placeholder": "Ej. Noche de chicas en Miami", "tripCreate.step1.title": "Ponele nombre a tu trip",
            "tripCreate.step2.title": "¿Cuándo es el trip?",
            "tripCreate.step3.subtitle": "Seleccioná los venues que querés visitar", "tripCreate.step3.title": "Elegí tus paradas",
            "tripCreate.summary.title": "Resumen del trip", "tripCreate.summary.titleLabel": "Título",
            "tripCreate.summary.venues": "Venues", "tripCreate.summary.venuesSelected": "%d seleccionados",
            "tripCreate.summary.visibility": "Visibilidad",
            "tripCreate.title": "Nuevo trip",
            "tripCreate.to": "Hasta",
            "tripCreate.venue.select.hint": "Tocá para seleccionar o deseleccionar este venue",
            "night.build.accessibility": "Armar mi noche", "night.build.hint": "Generar una ruta de venues según tu vibe",
            "night.defaultTitle": "Mi noche",
            "night.noMatch": "No encontramos venues para ese vibe. Probá otro.",
            "night.prompt.hint": "Describí la noche que buscás", "night.prompt.label": "Describir la noche",
            "night.prompt.placeholder": "Ej. algo relajado con buena música",
            "night.save.hint": "Guardar esta noche como un trip",
            "night.stop": "Parada %d", "night.stop.hint": "Detalle de esta parada de la ruta",
            "night.vibe.hint": "Tocá para seleccionar este vibe",
            "table.applePay": "Pagar con Apple Pay", "table.applePay.hint": "Procesa el depósito de la mesa usando Apple Pay", "table.applePay.hint.label": "Pagar depósito con Apple Pay",
            "table.banner.subtitle": "Reservá tu mesa VIP",
            "table.card.pay": "Pagar depósito con tarjeta", "table.card.pay.hint": "Abre el formulario para pagar el depósito con tarjeta de crédito o débito",
            "table.close": "Cerrar", "table.close.hint": "Cerrar la reservación de mesa",
            "table.deposit": "depósito",
            "table.guestCount": "Cantidad de invitados",
            "table.guests.hint": "Selecciona %d invitados para la mesa", "table.guests.label": "%d invitados",
            "table.minSpend.label": "Consumo mínimo",
            "table.package.hint": "Seleccioná este paquete de mesa. Depósito: %@",
            "table.paymentError.generic": "No pudimos procesar el pago. Intentá de nuevo.",
            "table.paymentError.label": "Error de pago: %@",
            "table.popular": "Popular",
            "table.reminder.body": "Tu reserva en %@ es en 30 minutos.",
            "table.reminder.title": "Tu mesa está por empezar",
            "table.slot.hint": "Selecciona las %@ como horario para la reservación", "table.slot.label": "Horario %@",
            "table.summary.depositNow": "Depósito ahora",
            "table.summary.guests": "Invitados", "table.summary.guestsValue": "%d personas",
            "table.summary.hint": "Muestra el resumen de la reservación incluyendo mesa, invitados y depósito",
            "table.summary.label": "Resumen de reservación",
            "table.summary.minSpend": "Consumo mín.",
            "table.summary.table": "Mesa",
            "table.summary.title": "Resumen",
            "table.timeSection": "Horario — Esta noche",
            "table.type": "Tipo de mesa",
            "table.vipTable": "Mesa VIP",
            "table.wallet.balance": "Balance: $%.2f",
            "table.wallet.name": "BarPass Wallet",
            "table.wallet.pay": "Pagar depósito con BarPass Wallet", "table.wallet.pay.hint": "Usa el saldo de tu billetera BarPass para pagar el depósito",
            "auth.apple.continue": "Continuar con Apple", "auth.apple.error": "No se pudo verificar tu Apple ID.", "auth.apple.hint": "Inicia sesión usando tu Apple ID",
            "auth.checkingSession": "Verificando sesión…",
            "auth.continueAsGuest": "Continuar como invitado", "auth.continueAsGuest.hint": "Omitir inicio de sesión",
            "auth.createAccount": "Crear cuenta", "auth.createAccount.hint": "Crear una cuenta nueva",
            "auth.dismissError": "Cerrar error", "auth.dismissError.hint": "Descarta el mensaje de error",
            "auth.enter": "Entrar", "auth.enter.hint": "Iniciar sesión en tu cuenta",
            "auth.error.connection": "Estamos teniendo problemas para conectar. Intentá de nuevo en un momento.",
            "auth.error.fillFields": "Completá todos los campos.",
            "auth.error.invalidEmail": "Ingresá un correo electrónico válido.",
            "auth.error.shortPassword": "La contraseña debe tener al menos 6 caracteres.",
            "auth.field.email": "Email", "auth.field.email.a11y": "Correo electrónico", "auth.field.email.hint": "Ingresa tu correo electrónico",
            "auth.field.password": "Contraseña", "auth.field.password.a11y": "Contraseña", "auth.field.password.hint": "Ingresa tu contraseña",
            "auth.forgotPassword": "¿Olvidaste tu contraseña?", "auth.forgotPassword.a11y": "Olvidé mi contraseña", "auth.forgotPassword.hint": "Recibirás un enlace para restablecerla",
            "auth.hidePassword": "Ocultar contraseña",
            "auth.legal.a11y.hint": "Abre los términos de servicio y política de privacidad", "auth.legal.a11y.label": "Términos y Privacidad",
            "auth.legal.and": "y",
            "auth.legal.prefix": "Al continuar aceptás nuestros",
            "auth.legal.privacy": "Privacidad",
            "auth.legal.terms": "Términos",
            "auth.or": "o",
            "auth.reset.cancel.hint": "Cerrar recuperación de contraseña",
            "auth.reset.checkEmail": "Revisa tu email",
            "auth.reset.error": "Estamos teniendo problemas para enviar el email de recuperación. Intentá de nuevo.",
            "auth.reset.field.hint": "Ingresa tu correo para recuperar contraseña",
            "auth.reset.ok": "OK", "auth.reset.ok.hint": "Confirmar cierre",
            "auth.reset.placeholder": "Tu email",
            "auth.reset.send": "Enviar", "auth.reset.send.hint": "Enviar enlace de recuperación",
            "auth.reset.sentMessage": "Si %@ tiene una cuenta, te enviamos un enlace para restablecer la contraseña.",
            "auth.reset.subtitle": "Te enviaremos un enlace a tu email para restablecerla.",
            "auth.reset.title": "Recuperar contraseña",
            "auth.showPassword": "Mostrar contraseña",
            "auth.socialProof": "+5,000 personas ya salen con BarPass", "auth.socialProof.a11y": "Más de 5,000 personas ya usan BarPass",
            "auth.state.loadingUser": "Cargando…", "auth.state.signingIn": "Entrando…", "auth.state.signingUp": "Creando cuenta…", "auth.state.success": "¡Listo!",
            "auth.tab.signIn": "Entrar", "auth.tab.signIn.a11y": "Iniciar sesión", "auth.tab.signIn.hint": "Cambiar a inicio de sesión",
            "auth.tab.signUp": "Registrarse", "auth.tab.signUp.a11y": "Crear cuenta", "auth.tab.signUp.hint": "Cambiar a registro",
            "auth.tagline": "Tu acceso a la mejor noche",
            "auth.togglePassword.hint": "Muestra u oculta la contraseña",
            "auth.tryAgain": "Intentar de nuevo",
            "posts.a11y.hint": "Publicación de un usuario sobre este venue", "posts.a11y.label": "Publicación de %@: %@",
            "posts.composer.placeholder": "¿Cómo está la noche?",
            "posts.composer.title": "Contanos sobre %@",
            "posts.empty": "Todavía no hay publicaciones. ¡Sé el primero!",
            "posts.guestHandle": "invitado", "posts.guestMode": "Estás publicando como invitado",
            "posts.post": "Publicar", "posts.post.hint": "Escribir una publicación sobre este venue",
            "posts.publish": "Publicar", "posts.publish.hint": "Publicar tu reseña",
            "posts.rating.drinks": "Tragos", "posts.rating.music": "Música", "posts.rating.vibe": "Vibe",
            "posts.title": "La gente dice",
            "hype.a11y.label": "Energía %d, personalidad de la noche: %@",
            "hype.artists.a11y": "Artistas que definen tu semana: %@",
            "hype.connect.hint": "Conectá tu cuenta de %@ para ver tu hype", "hype.connect.label": "Conectar %@",
            "hype.connectSpotify": "Conectar Spotify",
            "hype.defining": "TE DEFINIERON ESTA SEMANA",
            "hype.denied": "Activá el acceso a música en Ajustes para ver tu hype.",
            "hype.energy": "Energía al %d%%",
            "hype.error": "No pudimos conectar con tu música. Intentá de nuevo.",
            "hype.loading": "Conectando tu música…",
            "hype.newDiscoveries.plural": "%d descubrimientos nuevos esta semana",
            "hype.newDiscoveries.singular": "%d descubrimiento nuevo esta semana",
            "hype.noData": "Todavía no tenemos datos suficientes de tu música.",
            "hype.notEntitled": "Apple Music todavía no está disponible. Probá con Spotify.",
            "hype.title": "Tu Hype Esta Semana 🔥",
            "hype.welcome.subtitle": "Conectá tu música para ver tu vibe de la semana",
            "hype.welcome.title": "Descubrí tu Hype",
            "ageGate.confirm": "Confirmar", "ageGate.confirm.a11y": "Confirmar edad", "ageGate.confirm.hint": "Confirmá tu fecha de nacimiento para continuar",
            "ageGate.dob": "Fecha de nacimiento", "ageGate.dob.hint": "Seleccioná tu fecha de nacimiento",
            "ageGate.privacy": "Tu fecha de nacimiento no se comparte con nadie.",
            "ageGate.rejected.a11y.hint": "No podés continuar sin cumplir la edad mínima", "ageGate.rejected.a11y.label": "Acceso denegado por edad",
            "ageGate.rejected.subtitle": "BarPass es solo para mayores de 21 años.",
            "ageGate.rejected.title": "Lo sentimos",
            "ageGate.subtitle": "BarPass tiene contenido de bares y clubes. Necesitamos verificar tu edad.",
            "ageGate.title": "Confirmá tu edad",
            "tripSocial.accept": "Aceptar", "tripSocial.accept.hint": "Aceptar la solicitud de este usuario",
            "tripSocial.badge.hint": "Insignia de reputación del usuario",
            "tripSocial.badge.new": "Nuevo", "tripSocial.badge.trustedPlanner": "Organizador confiable", "tripSocial.badge.verified": "Verificado",
            "tripSocial.closeModal.hint": "Cerrar la lista de solicitudes",
            "tripSocial.noRequests": "No hay solicitudes pendientes.",
            "tripSocial.rating.hiddenNote": "Tu calificación es anónima y no se comparte directamente.",
            "tripSocial.rating.title": "Calificá a %@",
            "tripSocial.reject": "Rechazar", "tripSocial.reject.hint": "Rechazar la solicitud de este usuario",
            "tripSocial.requestsTitle": "Solicitudes para %@",
            "tripSocial.send": "Enviar", "tripSocial.send.hint": "Enviar tu calificación",
            "tripSocial.signal.score": "Puntaje", "tripSocial.signal.trips": "Trips",
            "tripSocial.stars.hint": "Calificar con %d estrellas", "tripSocial.stars.plural": "%d estrellas", "tripSocial.stars.singular": "%d estrella",
            "tripSocial.tag.good_vibe": "Buena onda", "tripSocial.tag.punctual": "Puntual", "tripSocial.tag.meshed_well": "Se llevó bien con el grupo",
            "tripSocial.tag.great_host": "Gran anfitrión", "tripSocial.tag.fun": "Divertido", "tripSocial.tag.chill": "Tranqui",
            "tripSocial.tag.hint": "Tocá para seleccionar esta etiqueta",
            "root.cart": "Carrito", "root.cart.hint": "Ver tu carrito de compras",
            "root.offline": "Sin conexión", "root.offline.a11y": "Sin conexión a internet", "root.offline.hint": "Algunas funciones pueden no estar disponibles",
            "root.orderEta": "~15 min",
            "root.orderSent": "Pedido enviado",
            "root.priorityEntry": "Priority Entry", "root.priorityEntry.hint": "Abrir opciones de acceso prioritario, mesas y tickets",
            "reservationConfirm.a11y.hint": "Muestra el código QR y detalles de tu reservación", "reservationConfirm.a11y.label": "Reservación confirmada en %@",
            "reservationConfirm.badge": "%d invitados",
            "reservationConfirm.date": "Fecha",
            "reservationConfirm.deposit": "Depósito", "reservationConfirm.depositPaid": "$%.0f pagado",
            "reservationConfirm.done": "Listo", "reservationConfirm.done.hint": "Cerrar la confirmación",
            "reservationConfirm.guests": "Invitados",
            "reservationConfirm.method": "Método de pago",
            "reservationConfirm.minSpend": "Consumo mín.",
            "reservationConfirm.share": "Compartir", "reservationConfirm.share.hint": "Compartir los detalles de tu reservación",
            "reservationConfirm.shareText": "¡Reservé una mesa en %@! Código: %@ · %@",
            "reservationConfirm.showQR": "Mostrá este QR al llegar al venue",
            "reservationConfirm.title": "¡Mesa reservada!",
            "priorityEntry.close.hint": "Cerrar Priority Entry",
            "priorityEntry.depositNote": "Los depósitos se aplican al consumo total en el venue. Cancelación gratuita hasta 2h antes.",
            "priorityEntry.header.subtitle": "Elegí cómo entrar esta noche",
            "priorityEntry.kicker": "PRIORITY ENTRY",
            "priorityEntry.skipLine": "Skip the Line", "priorityEntry.skipLine.badge": "Desde $25", "priorityEntry.skipLine.sub": "Entrá sin esperar en la fila",
            "priorityEntry.specialNight": "Noche especial",
            "priorityEntry.tickets": "Tickets de evento", "priorityEntry.tickets.badge": "Desde $15", "priorityEntry.tickets.sub": "Asegurá tu lugar en el evento",
            "priorityEntry.vipTable": "Mesa VIP", "priorityEntry.vipTable.badge": "Desde $150", "priorityEntry.vipTable.sub": "Reservá tu mesa con servicio de botella",
            "plan.buildButton": "Armar mi plan", "plan.buildButton.hint": "Generar un plan de noche con IA",
            "plan.headerSubtitle": "Contame qué buscás y armo tu ruta perfecta",
            "plan.headerTitle": "Tu concierge de noche",
            "plan.loadSaved.hint": "Cargar este plan guardado",
            "plan.nightPlan.kicker": "TU PLAN DE NOCHE",
            "plan.promptPlaceholder": "Ej. algo con buena música, sin mucho cover, cerca de Brickell…",
            "plan.quickIdeas": "Ideas rápidas",
            "plan.save": "Guardar", "plan.save.hint": "Guardar este plan",
            "plan.savedPlans": "Planes guardados",
            "plan.share": "Compartir", "plan.share.hint": "Compartir este plan",
            "plan.suggestion.birthday": "Es mi cumpleaños, quiero algo especial",
            "plan.suggestion.brickell": "Algo cerca de Brickell",
            "plan.suggestion.budget": "Algo económico para esta noche",
            "plan.suggestion.different": "Sorprendeme con algo diferente",
            "plan.suggestion.dinnerClub": "Cena y después club",
            "plan.suggestion.friends": "Salida con amigas",
            "plan.suggestion.hint": "Usar esta sugerencia como tu prompt",
            "plan.suggestion.houseMusic": "Lugares con house music",
            "plan.suggestion.noCover": "Sin cover",
            "cart.applePay.a11y": "Pagar con Apple Pay", "cart.applePay.hint": "Procesa el pago usando Apple Pay", "cart.applePay.pay": "Pay",
            "cart.clear": "Vaciar", "cart.clear.a11y": "Vaciar carrito", "cart.clear.hint": "Eliminar todos los artículos del carrito",
            "cart.close.a11y": "Cerrar carrito", "cart.close.hint": "Cerrar el carrito de compras",
            "cart.decreaseQty": "Reducir cantidad", "cart.decreaseQty.hint": "Resta uno a la cantidad del artículo",
            "cart.empty.subtitle": "Agregá artículos desde un venue para verlos acá.",
            "cart.empty.title": "Tu carrito está vacío",
            "cart.increaseQty": "Aumentar cantidad", "cart.increaseQty.hint": "Suma uno a la cantidad del artículo",
            "cart.item.a11y.hint": "Artículo en el carrito, precio $%.2f por unidad, cantidad %d",
            "cart.item.perUnit": "$%.2f c/u",
            "cart.payWithCard": "Pagar con tarjeta", "cart.payWithCard.hint": "Abre el formulario de pago con tarjeta de crédito o débito",
            "cart.payWithWallet": "Pagar con BarPass Wallet", "cart.payWithWallet.hint": "Usa el saldo de tu billetera BarPass para pagar",
            "cart.serviceFee": "Cargo de servicio",
            "cart.subtotal": "Subtotal",
            "cart.title": "Carrito",
            "cart.topUp": "Cargar BarPass Wallet", "cart.topUp.hint": "Abre la pantalla para agregar saldo a tu billetera",
            "cart.topUp.insufficient": "Balance: $%.2f — no alcanza para esta orden",
            "cart.topUp.subtitle": "Cargá saldo y pagá más rápido la próxima vez",
            "cart.total": "Total",
        ],
        .en: [
            "tab.tonight": "Tonight", "tab.explore": "Explore", "tab.trips": "Trips",
            "tab.plan": "Plan", "tab.me": "Me",
            "greet.morning": "Good morning", "greet.afternoon": "Good afternoon", "greet.night": "Good evening",
            "home.where": "Where to tonight?",
            "profile.language": "Language",
            "profile.points": "BarPass Points", "profile.nextLevel": "Next level",
            "profile.howToEarn": "How to earn points",
            "profile.checkins": "Check-ins", "profile.reviews": "Reviews", "profile.invited": "Invited",
            "explore.search": "Search venues…",
            "trips.title": "Trips", "trips.subtitle": "Plan your night with your crew",
            "trips.new": "New", "trips.mine": "My trips",
            "night.question": "What kind of night?",
            "night.hint": "Pick a vibe or describe it. I'll build the night.",
            "night.build": "Build my night", "night.rebuild": "Build another one",
            "night.yours": "Your night", "night.save": "Save as Trip",

            "home.mood.empty": "Nothing open for that mood right now.",
            "home.mood.count": "%@ · %d places",
            "home.mood.more": "More for this mood",
            "home.favorites": "❤️ Your favorites",
            "home.forYou": "🎵 Tonight, just for you",
            "home.eventsTonight": "🎟️ Tonight",
            "home.trending": "🔥 Trending now",
            "home.happyHour": "🍹 Happy Hour now",
            "home.openNow": "⚡ Open now",

            "profile.wallet.balance": "Balance: $%.2f — tap to top up",
            "profile.passes.title": "My passes & orders",
            "profile.passes.subtitle": "Purchase and pass history",
            "profile.games.title": "Games & missions",
            "profile.games.subtitle": "Daily trivia and missions for extra XP",
            "profile.earn.checkin": "Check in at a venue (×%d)",
            "profile.earn.review": "Photo review (×%d)",
            "profile.earn.trip": "Create or complete a trip (×%d)",
            "profile.earn.share": "Share a venue (×%d)",
            "profile.theme": "Theme",
            "profile.appearance": "Appearance",
            "profile.autoplay.title": "Auto-play music",
            "profile.autoplay.subtitle": "Plays your Apple Music when you open the app",
            "profile.account": "Account",
            "profile.account.activeSession": "Active session",
            "profile.account.signOut": "Sign out",
            "profile.account.guest": "You're in guest mode",
            "profile.account.signIn": "Sign in",
            "profile.level.max": "Max level reached 🏆",
            "profile.level.progress": "%d BPX to reach %@",

            // MARK: - Bulk view-text migration (Explore, Trips, Table, Auth, Posts, Hype, AgeGate, TripSocial, Root, ReservationConfirm, PriorityEntry, Plan, Cart)
            "explore.title": "Explore",
            "explore.toggleMap": "View map", "explore.toggleList": "View list",
            "explore.toggleView.hint": "Switch between map and list view",
            "explore.search.label": "Search venues", "explore.search.hint": "Search venues by name or location",
            "explore.clearSearch": "Clear search", "explore.clearSearch.hint": "Clear the search text",
            "explore.centerMap": "Center map", "explore.centerMap.hint": "Return to map center",
            "explore.layer.all": "All", "explore.layer.trending": "Trending", "explore.layer.happyHour": "Happy Hour",
            "explore.layer.noCover": "No Cover", "explore.layer.rooftops": "Rooftops", "explore.layer.liveMusic": "Live Music",
            "explore.cluster.label": "%d venues", "explore.cluster.hint": "Zoom in to see individual venues",
            "explore.marker.hint": "Venue on the map. %@. Rating: %@",
            "explore.openBadge": "Open", "explore.trendingBadge": "🔥 Trending",
            "explore.viewDetail.hint": "View details for %@", "explore.filterBy.hint": "Filter venues by %@",
            "explore.empty.noFilters": "No venues match these filters",
            "explore.empty.noResults": "No results for \"%@\"",
            "explore.empty.hint": "Try another name, neighborhood, or clear the filters.",
            "explore.listRow.hint": "%@. %@. Rating: %@",
            "trips.createNew": "Create new trip", "trips.createNew.hint": "Start creating a new trip",
            "trips.delete": "Delete", "trips.delete.hint": "Permanently delete this trip",
            "trips.empty.cta": "Create my first trip", "trips.empty.cta.hint": "Open the assistant to build a new trip",
            "trips.empty.subtitle": "Plan a night with your crew and save it as a trip.",
            "trips.empty.title": "You don't have any trips yet",
            "trips.error.title": "Something went wrong",
            "trips.openDetail.hint": "Open this trip's details",
            "trips.planCount.plural": "%d plans", "trips.planCount.singular": "%d plan",
            "trips.retry": "Retry", "trips.retry.hint": "Try loading trips again",
            "trips.status.active": "Active", "trips.status.completed": "Completed", "trips.status.planning": "Planning",
            "trips.stopsCount": "%d stops",
            "trips.yourTrips": "Your Trips", "trips.yourTrips.hint": "List of your saved trips",
            "tripCreate.back": "Back", "tripCreate.back.hint": "Go back to the previous step",
            "tripCreate.cancel": "Cancel", "tripCreate.cancel.hint": "Cancel creating the trip",
            "tripCreate.city": "City", "tripCreate.city.hint": "Enter the destination city", "tripCreate.city.placeholder": "e.g. Miami",
            "tripCreate.createButton": "Create trip", "tripCreate.createButton.hint": "Confirm and create the trip",
            "tripCreate.endDate": "End date", "tripCreate.endDate.hint": "Choose the trip's end date",
            "tripCreate.from": "From",
            "tripCreate.next": "Next", "tripCreate.next.hint": "Continue to the next step",
            "tripCreate.startDate": "Start date", "tripCreate.startDate.hint": "Choose the trip's start date",
            "tripCreate.step1.hint": "Enter your trip's title", "tripCreate.step1.label": "Trip title",
            "tripCreate.step1.placeholder": "e.g. Girls' night in Miami", "tripCreate.step1.title": "Name your trip",
            "tripCreate.step2.title": "When is the trip?",
            "tripCreate.step3.subtitle": "Select the venues you want to visit", "tripCreate.step3.title": "Pick your stops",
            "tripCreate.summary.title": "Trip summary", "tripCreate.summary.titleLabel": "Title",
            "tripCreate.summary.venues": "Venues", "tripCreate.summary.venuesSelected": "%d selected",
            "tripCreate.summary.visibility": "Visibility",
            "tripCreate.title": "New trip",
            "tripCreate.to": "To",
            "tripCreate.venue.select.hint": "Tap to select or deselect this venue",
            "night.build.accessibility": "Build my night", "night.build.hint": "Generate a venue route based on your vibe",
            "night.defaultTitle": "My night",
            "night.noMatch": "We couldn't find venues for that vibe. Try another one.",
            "night.prompt.hint": "Describe the night you're looking for", "night.prompt.label": "Describe the night",
            "night.prompt.placeholder": "e.g. something chill with good music",
            "night.save.hint": "Save this night as a trip",
            "night.stop": "Stop %d", "night.stop.hint": "Details for this stop on the route",
            "night.vibe.hint": "Tap to select this vibe",
            "table.applePay": "Pay with Apple Pay", "table.applePay.hint": "Process the table deposit using Apple Pay", "table.applePay.hint.label": "Pay deposit with Apple Pay",
            "table.banner.subtitle": "Reserve your VIP table",
            "table.card.pay": "Pay deposit with card", "table.card.pay.hint": "Open the form to pay the deposit with a credit or debit card",
            "table.close": "Close", "table.close.hint": "Close the table reservation",
            "table.deposit": "deposit",
            "table.guestCount": "Number of guests",
            "table.guests.hint": "Select %d guests for the table", "table.guests.label": "%d guests",
            "table.minSpend.label": "Minimum spend",
            "table.package.hint": "Select this table package. Deposit: %@",
            "table.paymentError.generic": "We couldn't process the payment. Please try again.",
            "table.paymentError.label": "Payment error: %@",
            "table.popular": "Popular",
            "table.reminder.body": "Your reservation at %@ is in 30 minutes.",
            "table.reminder.title": "Your table is about to start",
            "table.slot.hint": "Select %@ as the reservation time", "table.slot.label": "Time slot %@",
            "table.summary.depositNow": "Deposit now",
            "table.summary.guests": "Guests", "table.summary.guestsValue": "%d people",
            "table.summary.hint": "Shows the reservation summary including table, guests, and deposit",
            "table.summary.label": "Reservation summary",
            "table.summary.minSpend": "Min. spend",
            "table.summary.table": "Table",
            "table.summary.title": "Summary",
            "table.timeSection": "Time — Tonight",
            "table.type": "Table type",
            "table.vipTable": "VIP Table",
            "table.wallet.balance": "Balance: $%.2f",
            "table.wallet.name": "BarPass Wallet",
            "table.wallet.pay": "Pay deposit with BarPass Wallet", "table.wallet.pay.hint": "Use your BarPass Wallet balance to pay the deposit",
            "auth.apple.continue": "Continue with Apple", "auth.apple.error": "We couldn't verify your Apple ID.", "auth.apple.hint": "Sign in using your Apple ID",
            "auth.checkingSession": "Checking session…",
            "auth.continueAsGuest": "Continue as guest", "auth.continueAsGuest.hint": "Skip sign in",
            "auth.createAccount": "Create account", "auth.createAccount.hint": "Create a new account",
            "auth.dismissError": "Dismiss error", "auth.dismissError.hint": "Dismiss the error message",
            "auth.enter": "Sign in", "auth.enter.hint": "Sign in to your account",
            "auth.error.connection": "We're having trouble connecting right now. Please try again in a moment.",
            "auth.error.fillFields": "Please fill in all fields.",
            "auth.error.invalidEmail": "Please enter a valid email address.",
            "auth.error.shortPassword": "Password must be at least 6 characters.",
            "auth.field.email": "Email", "auth.field.email.a11y": "Email address", "auth.field.email.hint": "Enter your email address",
            "auth.field.password": "Password", "auth.field.password.a11y": "Password", "auth.field.password.hint": "Enter your password",
            "auth.forgotPassword": "Forgot your password?", "auth.forgotPassword.a11y": "Forgot my password", "auth.forgotPassword.hint": "You'll receive a link to reset it",
            "auth.hidePassword": "Hide password",
            "auth.legal.a11y.hint": "Opens the terms of service and privacy policy", "auth.legal.a11y.label": "Terms and Privacy",
            "auth.legal.and": "and",
            "auth.legal.prefix": "By continuing you agree to our",
            "auth.legal.privacy": "Privacy",
            "auth.legal.terms": "Terms",
            "auth.or": "or",
            "auth.reset.cancel.hint": "Close password recovery",
            "auth.reset.checkEmail": "Check your email",
            "auth.reset.error": "We're having trouble sending the reset email. Please try again.",
            "auth.reset.field.hint": "Enter your email to recover your password",
            "auth.reset.ok": "OK", "auth.reset.ok.hint": "Confirm close",
            "auth.reset.placeholder": "Your email",
            "auth.reset.send": "Send", "auth.reset.send.hint": "Send the recovery link",
            "auth.reset.sentMessage": "If %@ has an account, a reset link has been sent.",
            "auth.reset.subtitle": "We'll send a link to your email to reset it.",
            "auth.reset.title": "Recover password",
            "auth.showPassword": "Show password",
            "auth.socialProof": "+5,000 people already go out with BarPass", "auth.socialProof.a11y": "Over 5,000 people already use BarPass",
            "auth.state.loadingUser": "Loading…", "auth.state.signingIn": "Signing in…", "auth.state.signingUp": "Creating account…", "auth.state.success": "Done!",
            "auth.tab.signIn": "Sign in", "auth.tab.signIn.a11y": "Sign in", "auth.tab.signIn.hint": "Switch to sign in",
            "auth.tab.signUp": "Sign up", "auth.tab.signUp.a11y": "Create account", "auth.tab.signUp.hint": "Switch to sign up",
            "auth.tagline": "Your access to the best night out",
            "auth.togglePassword.hint": "Shows or hides the password",
            "auth.tryAgain": "Try again",
            "posts.a11y.hint": "A user's post about this venue", "posts.a11y.label": "Post by %@: %@",
            "posts.composer.placeholder": "How's the night going?",
            "posts.composer.title": "Tell us about %@",
            "posts.empty": "No posts yet. Be the first!",
            "posts.guestHandle": "guest", "posts.guestMode": "You're posting as a guest",
            "posts.post": "Post", "posts.post.hint": "Write a post about this venue",
            "posts.publish": "Post", "posts.publish.hint": "Publish your review",
            "posts.rating.drinks": "Drinks", "posts.rating.music": "Music", "posts.rating.vibe": "Vibe",
            "posts.title": "What people are saying",
            "hype.a11y.label": "Energy %d, night personality: %@",
            "hype.artists.a11y": "Artists that defined your week: %@",
            "hype.connect.hint": "Connect your %@ account to see your hype", "hype.connect.label": "Connect %@",
            "hype.connectSpotify": "Connect Spotify",
            "hype.defining": "DEFINED YOUR WEEK",
            "hype.denied": "Enable music access in Settings to see your hype.",
            "hype.energy": "Energy at %d%%",
            "hype.error": "We couldn't connect to your music. Please try again.",
            "hype.loading": "Connecting your music…",
            "hype.newDiscoveries.plural": "%d new discoveries this week",
            "hype.newDiscoveries.singular": "%d new discovery this week",
            "hype.noData": "We don't have enough data about your music yet.",
            "hype.notEntitled": "Apple Music isn't available yet. Try Spotify instead.",
            "hype.title": "Your Hype This Week 🔥",
            "hype.welcome.subtitle": "Connect your music to see your weekly vibe",
            "hype.welcome.title": "Discover Your Hype",
            "ageGate.confirm": "Confirm", "ageGate.confirm.a11y": "Confirm age", "ageGate.confirm.hint": "Confirm your date of birth to continue",
            "ageGate.dob": "Date of birth", "ageGate.dob.hint": "Select your date of birth",
            "ageGate.privacy": "Your date of birth is never shared with anyone.",
            "ageGate.rejected.a11y.hint": "You can't continue without meeting the minimum age", "ageGate.rejected.a11y.label": "Access denied due to age",
            "ageGate.rejected.subtitle": "BarPass is only for those 21 and older.",
            "ageGate.rejected.title": "We're sorry",
            "ageGate.subtitle": "BarPass features bar and club content. We need to verify your age.",
            "ageGate.title": "Confirm your age",
            "tripSocial.accept": "Accept", "tripSocial.accept.hint": "Accept this user's request",
            "tripSocial.badge.hint": "User's reputation badge",
            "tripSocial.badge.new": "New", "tripSocial.badge.trustedPlanner": "Trusted planner", "tripSocial.badge.verified": "Verified",
            "tripSocial.closeModal.hint": "Close the requests list",
            "tripSocial.noRequests": "No pending requests.",
            "tripSocial.rating.hiddenNote": "Your rating is anonymous and not shared directly.",
            "tripSocial.rating.title": "Rate %@",
            "tripSocial.reject": "Reject", "tripSocial.reject.hint": "Reject this user's request",
            "tripSocial.requestsTitle": "Requests for %@",
            "tripSocial.send": "Send", "tripSocial.send.hint": "Send your rating",
            "tripSocial.signal.score": "Score", "tripSocial.signal.trips": "Trips",
            "tripSocial.stars.hint": "Rate %d stars", "tripSocial.stars.plural": "%d stars", "tripSocial.stars.singular": "%d star",
            "tripSocial.tag.good_vibe": "Good vibe", "tripSocial.tag.punctual": "Punctual", "tripSocial.tag.meshed_well": "Meshed well with the group",
            "tripSocial.tag.great_host": "Great host", "tripSocial.tag.fun": "Fun", "tripSocial.tag.chill": "Chill",
            "tripSocial.tag.hint": "Tap to select this tag",
            "root.cart": "Cart", "root.cart.hint": "View your shopping cart",
            "root.offline": "No connection", "root.offline.a11y": "No internet connection", "root.offline.hint": "Some features may not be available",
            "root.orderEta": "~15 min",
            "root.orderSent": "Order sent",
            "root.priorityEntry": "Priority Entry", "root.priorityEntry.hint": "Open priority entry, table, and ticket options",
            "reservationConfirm.a11y.hint": "Shows the QR code and details for your reservation", "reservationConfirm.a11y.label": "Reservation confirmed at %@",
            "reservationConfirm.badge": "%d guests",
            "reservationConfirm.date": "Date",
            "reservationConfirm.deposit": "Deposit", "reservationConfirm.depositPaid": "$%.0f paid",
            "reservationConfirm.done": "Done", "reservationConfirm.done.hint": "Close the confirmation",
            "reservationConfirm.guests": "Guests",
            "reservationConfirm.method": "Payment method",
            "reservationConfirm.minSpend": "Min. spend",
            "reservationConfirm.share": "Share", "reservationConfirm.share.hint": "Share your reservation details",
            "reservationConfirm.shareText": "I booked a table at %@! Code: %@ · %@",
            "reservationConfirm.showQR": "Show this QR code when you arrive at the venue",
            "reservationConfirm.title": "Table reserved!",
            "priorityEntry.close.hint": "Close Priority Entry",
            "priorityEntry.depositNote": "Deposits apply toward your total spend at the venue. Free cancellation up to 2h before.",
            "priorityEntry.header.subtitle": "Choose how you want to get in tonight",
            "priorityEntry.kicker": "PRIORITY ENTRY",
            "priorityEntry.skipLine": "Skip the Line", "priorityEntry.skipLine.badge": "From $25", "priorityEntry.skipLine.sub": "Get in without waiting in line",
            "priorityEntry.specialNight": "Special night",
            "priorityEntry.tickets": "Event tickets", "priorityEntry.tickets.badge": "From $15", "priorityEntry.tickets.sub": "Secure your spot at the event",
            "priorityEntry.vipTable": "VIP Table", "priorityEntry.vipTable.badge": "From $150", "priorityEntry.vipTable.sub": "Reserve your table with bottle service",
            "plan.buildButton": "Build my plan", "plan.buildButton.hint": "Generate an AI-powered night plan",
            "plan.headerSubtitle": "Tell me what you're looking for and I'll build your perfect route",
            "plan.headerTitle": "Your night concierge",
            "plan.loadSaved.hint": "Load this saved plan",
            "plan.nightPlan.kicker": "YOUR NIGHT PLAN",
            "plan.promptPlaceholder": "e.g. something with good music, not too much cover, near Brickell…",
            "plan.quickIdeas": "Quick ideas",
            "plan.save": "Save", "plan.save.hint": "Save this plan",
            "plan.savedPlans": "Saved plans",
            "plan.share": "Share", "plan.share.hint": "Share this plan",
            "plan.suggestion.birthday": "It's my birthday, I want something special",
            "plan.suggestion.brickell": "Something near Brickell",
            "plan.suggestion.budget": "Something budget-friendly tonight",
            "plan.suggestion.different": "Surprise me with something different",
            "plan.suggestion.dinnerClub": "Dinner then a club",
            "plan.suggestion.friends": "Girls' night out",
            "plan.suggestion.hint": "Use this suggestion as your prompt",
            "plan.suggestion.houseMusic": "Spots with house music",
            "plan.suggestion.noCover": "No cover",
            "cart.applePay.a11y": "Pay with Apple Pay", "cart.applePay.hint": "Process the payment using Apple Pay", "cart.applePay.pay": "Pay",
            "cart.clear": "Clear", "cart.clear.a11y": "Clear cart", "cart.clear.hint": "Remove all items from the cart",
            "cart.close.a11y": "Close cart", "cart.close.hint": "Close the shopping cart",
            "cart.decreaseQty": "Decrease quantity", "cart.decreaseQty.hint": "Subtract one from the item quantity",
            "cart.empty.subtitle": "Add items from a venue to see them here.",
            "cart.empty.title": "Your cart is empty",
            "cart.increaseQty": "Increase quantity", "cart.increaseQty.hint": "Add one to the item quantity",
            "cart.item.a11y.hint": "Item in cart, price $%.2f each, quantity %d",
            "cart.item.perUnit": "$%.2f each",
            "cart.payWithCard": "Pay with card", "cart.payWithCard.hint": "Open the payment form for credit or debit card",
            "cart.payWithWallet": "Pay with BarPass Wallet", "cart.payWithWallet.hint": "Use your BarPass Wallet balance to pay",
            "cart.serviceFee": "Service fee",
            "cart.subtotal": "Subtotal",
            "cart.title": "Cart",
            "cart.topUp": "Top up BarPass Wallet", "cart.topUp.hint": "Open the screen to add balance to your wallet",
            "cart.topUp.insufficient": "Balance: $%.2f — not enough for this order",
            "cart.topUp.subtitle": "Add balance and pay faster next time",
            "cart.total": "Total",
        ],
        .pt: [
            "tab.tonight": "Tonight", "tab.explore": "Explorar", "tab.trips": "Trips",
            "tab.plan": "Plano", "tab.me": "Eu",
            "greet.morning": "Bom dia", "greet.afternoon": "Boa tarde", "greet.night": "Boa noite",
            "home.where": "Para onde hoje à noite?",
            "profile.language": "Idioma",
            "profile.points": "BarPass Points", "profile.nextLevel": "Próximo nível",
            "profile.howToEarn": "Como ganhar pontos",
            "profile.checkins": "Check-ins", "profile.reviews": "Avaliações", "profile.invited": "Convidados",
            "explore.search": "Buscar lugares…",
            "trips.title": "Trips", "trips.subtitle": "Planeje sua noite com sua galera",
            "trips.new": "Novo", "trips.mine": "Meus trips",
            "night.question": "Que noite você quer?",
            "night.hint": "Escolha um vibe ou descreva. Eu monto a noite.",
            "night.build": "Montar minha noite", "night.rebuild": "Montar outra",
            "night.yours": "Sua noite", "night.save": "Salvar como Trip",

            "home.mood.empty": "Nada aberto para esse mood agora.",
            "home.mood.count": "%@ · %d lugares",
            "home.mood.more": "Mais para esse mood",
            "home.favorites": "❤️ Seus favoritos",
            "home.forYou": "🎵 Hoje à noite, para você",
            "home.eventsTonight": "🎟️ Hoje à noite",
            "home.trending": "🔥 Trending agora",
            "home.happyHour": "🍹 Happy Hour ativo",
            "home.openNow": "⚡ Abertos agora",

            "profile.wallet.balance": "Saldo: $%.2f — toque para recarregar",
            "profile.passes.title": "Meus passes e pedidos",
            "profile.passes.subtitle": "Histórico de compras e passes",
            "profile.games.title": "Jogos e missões",
            "profile.games.subtitle": "Trivia diária e missões com XP extra",
            "profile.earn.checkin": "Check-in em um local (×%d)",
            "profile.earn.review": "Avaliação com foto (×%d)",
            "profile.earn.trip": "Criar ou completar um trip (×%d)",
            "profile.earn.share": "Compartilhar um local (×%d)",
            "profile.theme": "Tema",
            "profile.appearance": "Aparência",
            "profile.autoplay.title": "Música automática",
            "profile.autoplay.subtitle": "Toca sua música do Apple Music ao abrir o app",
            "profile.account": "Conta",
            "profile.account.activeSession": "Sessão ativa",
            "profile.account.signOut": "Sair",
            "profile.account.guest": "Você está no modo convidado",
            "profile.account.signIn": "Entrar",
            "profile.level.max": "Nível máximo alcançado 🏆",
            "profile.level.progress": "%d BPX para chegar a %@",

            // MARK: - Bulk view-text migration (Explore, Trips, Table, Auth, Posts, Hype, AgeGate, TripSocial, Root, ReservationConfirm, PriorityEntry, Plan, Cart)
            "explore.title": "Explorar",
            "explore.toggleMap": "Ver mapa", "explore.toggleList": "Ver lista",
            "explore.toggleView.hint": "Alternar entre visualização de mapa e lista",
            "explore.search.label": "Buscar locais", "explore.search.hint": "Buscar locais por nome ou localização",
            "explore.clearSearch": "Limpar busca", "explore.clearSearch.hint": "Apagar o texto da busca",
            "explore.centerMap": "Centralizar mapa", "explore.centerMap.hint": "Voltar ao centro do mapa",
            "explore.layer.all": "Todos", "explore.layer.trending": "Trending", "explore.layer.happyHour": "Happy Hour",
            "explore.layer.noCover": "Sem cover", "explore.layer.rooftops": "Rooftops", "explore.layer.liveMusic": "Música ao vivo",
            "explore.cluster.label": "%d locais", "explore.cluster.hint": "Aproxime o zoom para ver locais individuais",
            "explore.marker.hint": "Local no mapa. %@. Avaliação: %@",
            "explore.openBadge": "Aberto", "explore.trendingBadge": "🔥 Trending",
            "explore.viewDetail.hint": "Ver detalhes de %@", "explore.filterBy.hint": "Filtrar locais por %@",
            "explore.empty.noFilters": "Nenhum local com esses filtros",
            "explore.empty.noResults": "Sem resultados para \"%@\"",
            "explore.empty.hint": "Tente outro nome, bairro ou remova os filtros.",
            "explore.listRow.hint": "%@. %@. Avaliação: %@",
            "trips.createNew": "Criar novo trip", "trips.createNew.hint": "Começar a criar um novo trip",
            "trips.delete": "Excluir", "trips.delete.hint": "Excluir este trip permanentemente",
            "trips.empty.cta": "Criar meu primeiro trip", "trips.empty.cta.hint": "Abrir o assistente para montar um novo trip",
            "trips.empty.subtitle": "Planeje uma noite com sua galera e salve como trip.",
            "trips.empty.title": "Você ainda não tem trips",
            "trips.error.title": "Algo deu errado",
            "trips.openDetail.hint": "Abrir os detalhes deste trip",
            "trips.planCount.plural": "%d planos", "trips.planCount.singular": "%d plano",
            "trips.retry": "Tentar novamente", "trips.retry.hint": "Tentar carregar os trips novamente",
            "trips.status.active": "Ativo", "trips.status.completed": "Concluído", "trips.status.planning": "Planejando",
            "trips.stopsCount": "%d paradas",
            "trips.yourTrips": "Seus Trips", "trips.yourTrips.hint": "Lista dos seus trips salvos",
            "tripCreate.back": "Voltar", "tripCreate.back.hint": "Voltar para a etapa anterior",
            "tripCreate.cancel": "Cancelar", "tripCreate.cancel.hint": "Cancelar a criação do trip",
            "tripCreate.city": "Cidade", "tripCreate.city.hint": "Digite a cidade de destino", "tripCreate.city.placeholder": "Ex. Miami",
            "tripCreate.createButton": "Criar trip", "tripCreate.createButton.hint": "Confirmar e criar o trip",
            "tripCreate.endDate": "Data final", "tripCreate.endDate.hint": "Escolha a data final do trip",
            "tripCreate.from": "De",
            "tripCreate.next": "Próximo", "tripCreate.next.hint": "Continuar para a próxima etapa",
            "tripCreate.startDate": "Data inicial", "tripCreate.startDate.hint": "Escolha a data inicial do trip",
            "tripCreate.step1.hint": "Digite o título do seu trip", "tripCreate.step1.label": "Título do trip",
            "tripCreate.step1.placeholder": "Ex. Noite das amigas em Miami", "tripCreate.step1.title": "Dê um nome ao seu trip",
            "tripCreate.step2.title": "Quando é o trip?",
            "tripCreate.step3.subtitle": "Selecione os locais que você quer visitar", "tripCreate.step3.title": "Escolha suas paradas",
            "tripCreate.summary.title": "Resumo do trip", "tripCreate.summary.titleLabel": "Título",
            "tripCreate.summary.venues": "Locais", "tripCreate.summary.venuesSelected": "%d selecionados",
            "tripCreate.summary.visibility": "Visibilidade",
            "tripCreate.title": "Novo trip",
            "tripCreate.to": "Até",
            "tripCreate.venue.select.hint": "Toque para selecionar ou desmarcar este local",
            "night.build.accessibility": "Montar minha noite", "night.build.hint": "Gerar uma rota de locais com base no seu vibe",
            "night.defaultTitle": "Minha noite",
            "night.noMatch": "Não encontramos locais para esse vibe. Tente outro.",
            "night.prompt.hint": "Descreva a noite que você procura", "night.prompt.label": "Descrever a noite",
            "night.prompt.placeholder": "Ex. algo tranquilo com boa música",
            "night.save.hint": "Salvar esta noite como um trip",
            "night.stop": "Parada %d", "night.stop.hint": "Detalhes desta parada da rota",
            "night.vibe.hint": "Toque para selecionar este vibe",
            "table.applePay": "Pagar com Apple Pay", "table.applePay.hint": "Processa o depósito da mesa usando Apple Pay", "table.applePay.hint.label": "Pagar depósito com Apple Pay",
            "table.banner.subtitle": "Reserve sua mesa VIP",
            "table.card.pay": "Pagar depósito com cartão", "table.card.pay.hint": "Abre o formulário para pagar o depósito com cartão de crédito ou débito",
            "table.close": "Fechar", "table.close.hint": "Fechar a reserva de mesa",
            "table.deposit": "depósito",
            "table.guestCount": "Número de convidados",
            "table.guests.hint": "Selecione %d convidados para a mesa", "table.guests.label": "%d convidados",
            "table.minSpend.label": "Consumo mínimo",
            "table.package.hint": "Selecione este pacote de mesa. Depósito: %@",
            "table.paymentError.generic": "Não conseguimos processar o pagamento. Tente novamente.",
            "table.paymentError.label": "Erro de pagamento: %@",
            "table.popular": "Popular",
            "table.reminder.body": "Sua reserva em %@ é em 30 minutos.",
            "table.reminder.title": "Sua mesa está prestes a começar",
            "table.slot.hint": "Selecione %@ como horário para a reserva", "table.slot.label": "Horário %@",
            "table.summary.depositNow": "Depósito agora",
            "table.summary.guests": "Convidados", "table.summary.guestsValue": "%d pessoas",
            "table.summary.hint": "Mostra o resumo da reserva incluindo mesa, convidados e depósito",
            "table.summary.label": "Resumo da reserva",
            "table.summary.minSpend": "Consumo mín.",
            "table.summary.table": "Mesa",
            "table.summary.title": "Resumo",
            "table.timeSection": "Horário — Hoje à noite",
            "table.type": "Tipo de mesa",
            "table.vipTable": "Mesa VIP",
            "table.wallet.balance": "Saldo: $%.2f",
            "table.wallet.name": "BarPass Wallet",
            "table.wallet.pay": "Pagar depósito com BarPass Wallet", "table.wallet.pay.hint": "Use o saldo da sua carteira BarPass para pagar o depósito",
            "auth.apple.continue": "Continuar com Apple", "auth.apple.error": "Não foi possível verificar seu Apple ID.", "auth.apple.hint": "Entre usando seu Apple ID",
            "auth.checkingSession": "Verificando sessão…",
            "auth.continueAsGuest": "Continuar como convidado", "auth.continueAsGuest.hint": "Pular login",
            "auth.createAccount": "Criar conta", "auth.createAccount.hint": "Criar uma nova conta",
            "auth.dismissError": "Fechar erro", "auth.dismissError.hint": "Descarta a mensagem de erro",
            "auth.enter": "Entrar", "auth.enter.hint": "Entrar na sua conta",
            "auth.error.connection": "Estamos com problemas para conectar agora. Tente novamente em instantes.",
            "auth.error.fillFields": "Preencha todos os campos.",
            "auth.error.invalidEmail": "Digite um endereço de email válido.",
            "auth.error.shortPassword": "A senha deve ter pelo menos 6 caracteres.",
            "auth.field.email": "Email", "auth.field.email.a11y": "Endereço de email", "auth.field.email.hint": "Digite seu endereço de email",
            "auth.field.password": "Senha", "auth.field.password.a11y": "Senha", "auth.field.password.hint": "Digite sua senha",
            "auth.forgotPassword": "Esqueceu sua senha?", "auth.forgotPassword.a11y": "Esqueci minha senha", "auth.forgotPassword.hint": "Você receberá um link para redefini-la",
            "auth.hidePassword": "Ocultar senha",
            "auth.legal.a11y.hint": "Abre os termos de serviço e a política de privacidade", "auth.legal.a11y.label": "Termos e Privacidade",
            "auth.legal.and": "e",
            "auth.legal.prefix": "Ao continuar você aceita nossos",
            "auth.legal.privacy": "Privacidade",
            "auth.legal.terms": "Termos",
            "auth.or": "ou",
            "auth.reset.cancel.hint": "Fechar recuperação de senha",
            "auth.reset.checkEmail": "Verifique seu email",
            "auth.reset.error": "Estamos com problemas para enviar o email de recuperação. Tente novamente.",
            "auth.reset.field.hint": "Digite seu email para recuperar a senha",
            "auth.reset.ok": "OK", "auth.reset.ok.hint": "Confirmar fechamento",
            "auth.reset.placeholder": "Seu email",
            "auth.reset.send": "Enviar", "auth.reset.send.hint": "Enviar o link de recuperação",
            "auth.reset.sentMessage": "Se %@ tiver uma conta, um link de redefinição foi enviado.",
            "auth.reset.subtitle": "Enviaremos um link para seu email para redefini-la.",
            "auth.reset.title": "Recuperar senha",
            "auth.showPassword": "Mostrar senha",
            "auth.socialProof": "+5.000 pessoas já saem com o BarPass", "auth.socialProof.a11y": "Mais de 5.000 pessoas já usam o BarPass",
            "auth.state.loadingUser": "Carregando…", "auth.state.signingIn": "Entrando…", "auth.state.signingUp": "Criando conta…", "auth.state.success": "Pronto!",
            "auth.tab.signIn": "Entrar", "auth.tab.signIn.a11y": "Entrar", "auth.tab.signIn.hint": "Mudar para login",
            "auth.tab.signUp": "Cadastrar", "auth.tab.signUp.a11y": "Criar conta", "auth.tab.signUp.hint": "Mudar para cadastro",
            "auth.tagline": "Seu acesso à melhor noite",
            "auth.togglePassword.hint": "Mostra ou oculta a senha",
            "auth.tryAgain": "Tentar novamente",
            "posts.a11y.hint": "Publicação de um usuário sobre este local", "posts.a11y.label": "Publicação de %@: %@",
            "posts.composer.placeholder": "Como está a noite?",
            "posts.composer.title": "Conte sobre %@",
            "posts.empty": "Ainda não há publicações. Seja o primeiro!",
            "posts.guestHandle": "convidado", "posts.guestMode": "Você está publicando como convidado",
            "posts.post": "Publicar", "posts.post.hint": "Escrever uma publicação sobre este local",
            "posts.publish": "Publicar", "posts.publish.hint": "Publicar sua avaliação",
            "posts.rating.drinks": "Bebidas", "posts.rating.music": "Música", "posts.rating.vibe": "Vibe",
            "posts.title": "O que as pessoas dizem",
            "hype.a11y.label": "Energia %d, personalidade da noite: %@",
            "hype.artists.a11y": "Artistas que definiram sua semana: %@",
            "hype.connect.hint": "Conecte sua conta do %@ para ver seu hype", "hype.connect.label": "Conectar %@",
            "hype.connectSpotify": "Conectar Spotify",
            "hype.defining": "DEFINIRAM SUA SEMANA",
            "hype.denied": "Ative o acesso à música nos Ajustes para ver seu hype.",
            "hype.energy": "Energia em %d%%",
            "hype.error": "Não conseguimos conectar à sua música. Tente novamente.",
            "hype.loading": "Conectando sua música…",
            "hype.newDiscoveries.plural": "%d novas descobertas esta semana",
            "hype.newDiscoveries.singular": "%d nova descoberta esta semana",
            "hype.noData": "Ainda não temos dados suficientes da sua música.",
            "hype.notEntitled": "O Apple Music ainda não está disponível. Experimente o Spotify.",
            "hype.title": "Seu Hype Desta Semana 🔥",
            "hype.welcome.subtitle": "Conecte sua música para ver seu vibe da semana",
            "hype.welcome.title": "Descubra seu Hype",
            "ageGate.confirm": "Confirmar", "ageGate.confirm.a11y": "Confirmar idade", "ageGate.confirm.hint": "Confirme sua data de nascimento para continuar",
            "ageGate.dob": "Data de nascimento", "ageGate.dob.hint": "Selecione sua data de nascimento",
            "ageGate.privacy": "Sua data de nascimento nunca é compartilhada com ninguém.",
            "ageGate.rejected.a11y.hint": "Você não pode continuar sem atingir a idade mínima", "ageGate.rejected.a11y.label": "Acesso negado por idade",
            "ageGate.rejected.subtitle": "O BarPass é apenas para maiores de 21 anos.",
            "ageGate.rejected.title": "Sentimos muito",
            "ageGate.subtitle": "O BarPass tem conteúdo de bares e clubes. Precisamos verificar sua idade.",
            "ageGate.title": "Confirme sua idade",
            "tripSocial.accept": "Aceitar", "tripSocial.accept.hint": "Aceitar o pedido deste usuário",
            "tripSocial.badge.hint": "Selo de reputação do usuário",
            "tripSocial.badge.new": "Novo", "tripSocial.badge.trustedPlanner": "Organizador confiável", "tripSocial.badge.verified": "Verificado",
            "tripSocial.closeModal.hint": "Fechar a lista de pedidos",
            "tripSocial.noRequests": "Nenhum pedido pendente.",
            "tripSocial.rating.hiddenNote": "Sua avaliação é anônima e não é compartilhada diretamente.",
            "tripSocial.rating.title": "Avalie %@",
            "tripSocial.reject": "Recusar", "tripSocial.reject.hint": "Recusar o pedido deste usuário",
            "tripSocial.requestsTitle": "Pedidos para %@",
            "tripSocial.send": "Enviar", "tripSocial.send.hint": "Enviar sua avaliação",
            "tripSocial.signal.score": "Pontuação", "tripSocial.signal.trips": "Trips",
            "tripSocial.stars.hint": "Avaliar com %d estrelas", "tripSocial.stars.plural": "%d estrelas", "tripSocial.stars.singular": "%d estrela",
            "tripSocial.tag.good_vibe": "Boa vibe", "tripSocial.tag.punctual": "Pontual", "tripSocial.tag.meshed_well": "Se deu bem com o grupo",
            "tripSocial.tag.great_host": "Ótimo anfitrião", "tripSocial.tag.fun": "Divertido", "tripSocial.tag.chill": "Tranquilo",
            "tripSocial.tag.hint": "Toque para selecionar esta tag",
            "root.cart": "Carrinho", "root.cart.hint": "Ver seu carrinho de compras",
            "root.offline": "Sem conexão", "root.offline.a11y": "Sem conexão com a internet", "root.offline.hint": "Alguns recursos podem não estar disponíveis",
            "root.orderEta": "~15 min",
            "root.orderSent": "Pedido enviado",
            "root.priorityEntry": "Priority Entry", "root.priorityEntry.hint": "Abrir opções de entrada prioritária, mesas e ingressos",
            "reservationConfirm.a11y.hint": "Mostra o código QR e os detalhes da sua reserva", "reservationConfirm.a11y.label": "Reserva confirmada em %@",
            "reservationConfirm.badge": "%d convidados",
            "reservationConfirm.date": "Data",
            "reservationConfirm.deposit": "Depósito", "reservationConfirm.depositPaid": "$%.0f pago",
            "reservationConfirm.done": "Pronto", "reservationConfirm.done.hint": "Fechar a confirmação",
            "reservationConfirm.guests": "Convidados",
            "reservationConfirm.method": "Método de pagamento",
            "reservationConfirm.minSpend": "Consumo mín.",
            "reservationConfirm.share": "Compartilhar", "reservationConfirm.share.hint": "Compartilhar os detalhes da sua reserva",
            "reservationConfirm.shareText": "Reservei uma mesa em %@! Código: %@ · %@",
            "reservationConfirm.showQR": "Mostre este QR ao chegar ao local",
            "reservationConfirm.title": "Mesa reservada!",
            "priorityEntry.close.hint": "Fechar Priority Entry",
            "priorityEntry.depositNote": "Os depósitos são aplicados ao consumo total no local. Cancelamento gratuito até 2h antes.",
            "priorityEntry.header.subtitle": "Escolha como entrar hoje à noite",
            "priorityEntry.kicker": "PRIORITY ENTRY",
            "priorityEntry.skipLine": "Skip the Line", "priorityEntry.skipLine.badge": "A partir de $25", "priorityEntry.skipLine.sub": "Entre sem esperar na fila",
            "priorityEntry.specialNight": "Noite especial",
            "priorityEntry.tickets": "Ingressos do evento", "priorityEntry.tickets.badge": "A partir de $15", "priorityEntry.tickets.sub": "Garanta seu lugar no evento",
            "priorityEntry.vipTable": "Mesa VIP", "priorityEntry.vipTable.badge": "A partir de $150", "priorityEntry.vipTable.sub": "Reserve sua mesa com serviço de garrafa",
            "plan.buildButton": "Montar meu plano", "plan.buildButton.hint": "Gerar um plano de noite com IA",
            "plan.headerSubtitle": "Me conte o que você procura e eu monto sua rota perfeita",
            "plan.headerTitle": "Seu concierge da noite",
            "plan.loadSaved.hint": "Carregar este plano salvo",
            "plan.nightPlan.kicker": "SEU PLANO DA NOITE",
            "plan.promptPlaceholder": "Ex. algo com boa música, sem muito cover, perto de Brickell…",
            "plan.quickIdeas": "Ideias rápidas",
            "plan.save": "Salvar", "plan.save.hint": "Salvar este plano",
            "plan.savedPlans": "Planos salvos",
            "plan.share": "Compartilhar", "plan.share.hint": "Compartilhar este plano",
            "plan.suggestion.birthday": "É meu aniversário, quero algo especial",
            "plan.suggestion.brickell": "Algo perto de Brickell",
            "plan.suggestion.budget": "Algo econômico para hoje à noite",
            "plan.suggestion.different": "Me surpreenda com algo diferente",
            "plan.suggestion.dinnerClub": "Jantar e depois balada",
            "plan.suggestion.friends": "Noite com as amigas",
            "plan.suggestion.hint": "Usar esta sugestão como seu prompt",
            "plan.suggestion.houseMusic": "Lugares com house music",
            "plan.suggestion.noCover": "Sem cover",
            "cart.applePay.a11y": "Pagar com Apple Pay", "cart.applePay.hint": "Processa o pagamento usando Apple Pay", "cart.applePay.pay": "Pay",
            "cart.clear": "Esvaziar", "cart.clear.a11y": "Esvaziar carrinho", "cart.clear.hint": "Remover todos os itens do carrinho",
            "cart.close.a11y": "Fechar carrinho", "cart.close.hint": "Fechar o carrinho de compras",
            "cart.decreaseQty": "Diminuir quantidade", "cart.decreaseQty.hint": "Subtrai um da quantidade do item",
            "cart.empty.subtitle": "Adicione itens de um local para vê-los aqui.",
            "cart.empty.title": "Seu carrinho está vazio",
            "cart.increaseQty": "Aumentar quantidade", "cart.increaseQty.hint": "Adiciona um à quantidade do item",
            "cart.item.a11y.hint": "Item no carrinho, preço $%.2f cada, quantidade %d",
            "cart.item.perUnit": "$%.2f cada",
            "cart.payWithCard": "Pagar com cartão", "cart.payWithCard.hint": "Abre o formulário de pagamento com cartão de crédito ou débito",
            "cart.payWithWallet": "Pagar com BarPass Wallet", "cart.payWithWallet.hint": "Use o saldo da sua carteira BarPass para pagar",
            "cart.serviceFee": "Taxa de serviço",
            "cart.subtotal": "Subtotal",
            "cart.title": "Carrinho",
            "cart.topUp": "Carregar BarPass Wallet", "cart.topUp.hint": "Abre a tela para adicionar saldo à sua carteira",
            "cart.topUp.insufficient": "Saldo: $%.2f — não é suficiente para este pedido",
            "cart.topUp.subtitle": "Adicione saldo e pague mais rápido da próxima vez",
            "cart.total": "Total",
        ],
    ]
}
